import json

CODING_PROBLEMS = []

def p(title, slug, diff, topics, companies, desc, examples, constraints, hints, tc, htc, sol, tl=1000):
    CODING_PROBLEMS.append({
        "title": title, "slug": slug, "difficulty": diff, "topics": topics,
        "companies": companies, "description": desc, "examples": examples,
        "constraints": constraints, "hints": hints, "test_cases": tc,
        "hidden_test_cases": htc, "solution": {"python": sol},
        "time_limit": tl, "memory_limit": 256
    })

# === EASY (35) ===
p("Two Sum","two-sum","easy",["arrays","hash-table"],["Amazon","Google","Meta"],"Given an array of integers nums and an integer target, return indices of the two numbers that add up to target.",[{"input":"nums = [2,7,11,15], target = 9","output":"[0,1]","explanation":""}],"2 <= nums.length <= 10^4",["Use a hash map to store complements"],[{"input":"4\n2 7 11 15\n9","output":"0 1"},{"input":"3\n3 2 4\n6","output":"1 2"}],[{"input":"2\n3 3\n6","output":"0 1"}],"def twoSum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        comp = target - n\n        if comp in seen: return [seen[comp], i]\n        seen[n] = i")

p("Reverse String","reverse-string","easy",["strings","two-pointers"],["Microsoft","Apple"],"Write a function that reverses a string.",[{"input":"hello","output":"olleh","explanation":""}],"1 <= s.length <= 10^5",["Use two pointers"],[{"input":"5\nhello","output":"olleh"},{"input":"1\nA","output":"A"}],[{"input":"7\nAbcdEfG","output":"GfEdcba"}],"def reverseString(s):\n    return s[::-1]")

p("Valid Parentheses","valid-parentheses","easy",["stack","strings"],["Amazon","Meta","Bloomberg"],"Given a string s containing just parentheses, determine if the input string is valid.",[{"input":"()","output":"true","explanation":""}],"1 <= s.length <= 10^4",["Use a stack"],[{"input":"2\n()","output":"true"},{"input":"3\n([])","output":"true"}],[{"input":"6\n([{}])","output":"true"}],"def isValid(s):\n    stack = []\n    mapping = {')':'(',']':'[','}':'{'}\n    for c in s:\n        if c in mapping:\n            if not stack or stack[-1] != mapping[c]: return False\n            stack.pop()\n        else: stack.append(c)\n    return not stack")

p("Maximum Subarray","maximum-subarray","easy",["arrays","dynamic-programming"],["Google","Amazon"],"Find the contiguous subarray with the largest sum.",[{"input":"nums = [-2,1,-3,4,-1,2,1,-5,4]","output":"6","explanation":""}],"1 <= nums.length <= 10^5",["Use Kadane's algorithm"],[{"input":"9\n-2 1 -3 4 -1 2 1 -5 4","output":"6"},{"input":"1\n1","output":"1"}],[{"input":"5\n5 4 -1 7 8","output":"23"}],"def maxSubArray(nums):\n    cur = max_sum = nums[0]\n    for n in nums[1:]:\n        cur = max(n, cur + n)\n        max_sum = max(max_sum, cur)\n    return max_sum")

p("Merge Two Sorted Lists","merge-two-sorted-lists","easy",["linked-list","recursion"],["Microsoft","Amazon"],"Merge two sorted linked lists into one sorted list.",[{"input":"list1 = [1,2,4], list2 = [1,3,4]","output":"[1,1,2,3,4,4]","explanation":""}],"Both lists are sorted",["Use a dummy node"],[{"input":"3\n1 2 4\n3\n1 3 4","output":"1 1 2 3 4 4"},{"input":"0\n\n0\n\n","output":""}],[{"input":"1\n2\n1\n1","output":"1 2"}],"def mergeTwoLists(l1, l2):\n    if not l1: return l2\n    if not l2: return l1\n    if l1.val <= l2.val:\n        l1.next = mergeTwoLists(l1.next, l2)\n        return l1\n    l2.next = mergeTwoLists(l1, l2.next)\n    return l2")

p("Best Time to Buy and Sell Stock","best-time-to-buy-sell-stock","easy",["arrays","dynamic-programming"],["Amazon","Meta"],"Find the maximum profit from buying and selling a stock once.",[{"input":"prices = [7,1,5,3,6,4]","output":"5","explanation":""}],"1 <= prices.length <= 10^5",["Track minimum price"],[{"input":"6\n7 1 5 3 6 4","output":"5"},{"input":"5\n7 6 4 3 1","output":"0"}],[{"input":"4\n2 4 1 7","output":"5"}],"def maxProfit(prices):\n    min_price = float('inf')\n    max_profit = 0\n    for p in prices:\n        min_price = min(min_price, p)\n        max_profit = max(max_profit, p - min_price)\n    return max_profit")

p("Binary Search","binary-search","easy",["arrays","searching"],["Microsoft","Amazon"],"Search for a target in a sorted array.",[{"input":"nums = [-1,0,3,5,9,12], target = 9","output":"4","explanation":""}],"O(log n) required",["Classic binary search"],[{"input":"6\n-1 0 3 5 9 12\n9","output":"4"},{"input":"6\n-1 0 3 5 9 12\n2","output":"-1"}],[{"input":"1\n5\n5","output":"0"}],"def search(nums, target):\n    lo, hi = 0, len(nums)-1\n    while lo <= hi:\n        mid = (lo+hi)//2\n        if nums[mid] == target: return mid\n        elif nums[mid] < target: lo = mid+1\n        else: hi = mid-1\n    return -1")

p("Climbing Stairs","climbing-stairs","easy",["dynamic-programming","math"],["Amazon","Apple"],"Climb n stairs using 1 or 2 steps. How many distinct ways?",[{"input":"n = 2","output":"2","explanation":""}],"1 <= n <= 45",["This is Fibonacci"],[{"input":"2","output":"2"},{"input":"3","output":"3"}],[{"input":"5","output":"8"}],"def climbStairs(n):\n    if n <= 2: return n\n    a, b = 1, 2\n    for _ in range(3, n+1):\n        a, b = b, a+b\n    return b")

p("Palindrome Number","palindrome-number","easy",["math"],["Google","Amazon"],"Determine if an integer is a palindrome.",[{"input":"121","output":"true","explanation":""}],"-2^31 <= x <= 2^31-1",["Reverse the number"],[{"input":"121","output":"true"},{"input":"-121","output":"false"}],[{"input":"10","output":"false"}],"def isPalindrome(x):\n    if x < 0: return False\n    return str(x) == str(x)[::-1]")

p("Remove Duplicates from Sorted Array","remove-duplicates-sorted-array","easy",["arrays","two-pointers"],["Amazon"],"Remove duplicates in-place and return new length.",[{"input":"nums = [1,1,2]","output":"2","explanation":""}],"1 <= nums.length <= 3*10^4",["Use two pointers"],[{"input":"3\n1 1 2","output":"2"},{"input":"10\n0 0 1 1 1 2 2 3 3 4","output":"5"}],[{"input":"1\n1","output":"1"}],"def removeDuplicates(nums):\n    if not nums: return 0\n    i = 0\n    for j in range(1, len(nums)):\n        if nums[j] != nums[i]:\n            i += 1\n            nums[i] = nums[j]\n    return i+1")

p("Contains Duplicate","contains-duplicate","easy",["arrays","hash-table"],["Amazon","Google"],"Return true if any value appears at least twice.",[{"input":"nums = [1,2,3,1]","output":"true","explanation":""}],"1 <= nums.length <= 10^5",["Use a set"],[{"input":"4\n1 2 3 1","output":"true"},{"input":"4\n1 2 3 4","output":"false"}],[{"input":"3\n1 1 1","output":"true"}],"def containsDuplicate(nums):\n    return len(nums) != len(set(nums))")

p("Single Number","single-number","easy",["arrays","bit-manipulation"],["Amazon","Google"],"Find the element that appears only once.",[{"input":"nums = [2,2,1]","output":"1","explanation":""}],"1 <= nums.length <= 3*10^4",["Use XOR"],[{"input":"3\n2 2 1","output":"1"},{"input":"5\n4 1 2 1 2","output":"4"}],[{"input":"1\n1","output":"1"}],"def singleNumber(nums):\n    result = 0\n    for n in nums: result ^= n\n    return result")

p("Fizz Buzz","fizz-buzz","easy",["math","strings"],["Amazon","Google"],"Return fizzbuzz array from 1 to n.",[{"input":"5","output":"1 2 Fizz 4 Buzz","explanation":""}],"1 <= n <= 10^4",["Check divisibility by 3 and 5"],[{"input":"5","output":"1 2 Fizz 4 Buzz"},{"input":"3","output":"1 2 Fizz"}],[{"input":"15","output":"1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz"}],"def fizzBuzz(n):\n    return ['Fizz'*(i%3==0)+'Buzz'*(i%5==0) or str(i) for i in range(1,n+1)]")

p("Power of Two","power-of-two","easy",["math","bit-manipulation"],["Amazon"],"Determine if n is a power of two.",[{"input":"16","output":"true","explanation":""}],"0 <= n <= 2^31 - 1",["Use bit manipulation"],[{"input":"16","output":"true"},{"input":"3","output":"false"}],[{"input":"1","output":"true"}],"def isPowerOfTwo(n):\n    return n > 0 and (n & (n-1)) == 0")

p("Valid Anagram","valid-anagram","easy",["strings","hash-table"],["Amazon","Meta"],"Determine if two strings are anagrams.",[{"input":"s = anagram, t = nagaram","output":"true","explanation":""}],"1 <= s.length, t.length <= 5*10^4",["Count character frequencies"],[{"input":"anagram\nnagaram","output":"true"},{"input":"rat\ncar","output":"false"}],[{"input":"a\na","output":"true"}],"def isAnagram(s, t):\n    return sorted(s) == sorted(t)")

p("First Unique Character in a String","first-unique-character","easy",["strings","hash-table"],["Amazon","Google"],"Find the first non-repeating character index.",[{"input":"leetcode","output":"0","explanation":""}],"1 <= s.length <= 10^5",["Count frequencies first"],[{"input":"leetcode","output":"0"},{"input":"aabb","output":"-1"}],[{"input":"loveleetcode","output":"2"}],"def firstUniqChar(s):\n    count = {}\n    for c in s: count[c] = count.get(c, 0) + 1\n    for i, c in enumerate(s):\n        if count[c] == 1: return i\n    return -1")

p("Count Primes","count-primes","easy",["math","arrays"],["Amazon"],"Count primes less than n.",[{"input":"10","output":"4","explanation":"Primes: 2,3,5,7"}],"0 <= n <= 5*10^6",["Use Sieve of Eratosthenes"],[{"input":"10","output":"4"},{"input":"0","output":"0"}],[{"input":"100","output":"25"}],"def countPrimes(n):\n    if n < 3: return 0\n    sieve = [True] * n\n    sieve[0] = sieve[1] = False\n    for i in range(2, int(n**0.5)+1):\n        if sieve[i]:\n            for j in range(i*i, n, i): sieve[j] = False\n    return sum(sieve)",2000)

p("Fibonacci Number","fibonacci-number","easy",["dynamic-programming","math"],["Amazon","Google"],"Return the nth Fibonacci number.",[{"input":"4","output":"3","explanation":"F(4)=3"}],"0 <= n <= 30",["Iterative approach is O(n)"],[{"input":"4","output":"3"},{"input":"2","output":"1"}],[{"input":"10","output":"55"}],"def fib(n):\n    if n <= 1: return n\n    a, b = 0, 1\n    for _ in range(2, n+1): a, b = b, a+b\n    return b")

p("Valid Palindrome","valid-palindrome","easy",["strings","two-pointers"],["Amazon","Meta"],"Check if a string is a palindrome considering only alphanumeric characters.",[{"input":"A man a plan a canal Panama","output":"true","explanation":""}],"1 <= s.length <= 2*10^5",["Use two pointers"],[{"input":"A man a plan a canal Panama","output":"true"},{"input":"race a car","output":"false"}],[{"input":" ","output":"true"}],"def isPalindrome(s):\n    s = ''.join(c.lower() for c in s if c.isalnum())\n    return s == s[::-1]")

p("Missing Number","missing-number","easy",["arrays","math","bit-manipulation"],["Amazon","Google"],"Find the missing number in array [0..n].",[{"input":"nums = [3,0,1]","output":"2","explanation":""}],"n == nums.length",["Use sum formula or XOR"],[{"input":"3\n3 0 1","output":"2"},{"input":"9\n9 6 4 2 3 5 7 0 1","output":"8"}],[{"input":"1\n0","output":"1"}],"def missingNumber(nums):\n    n = len(nums)\n    return n*(n+1)//2 - sum(nums)")

p("Majority Element","majority-element","easy",["arrays","hash-table","sorting"],["Amazon","Google"],"Find the element appearing more than n/2 times.",[{"input":"nums = [2,2,1]","output":"2","explanation":""}],"1 <= nums.length <= 5*10^4",["Boyer-Moore voting algorithm"],[{"input":"3\n2 2 1","output":"2"},{"input":"7\n2 2 1 1 1 2 2","output":"2"}],[{"input":"1\n1","output":"1"}],"def majorityElement(nums):\n    count = candidate = 0\n    for n in nums:\n        if count == 0: candidate = n\n        count += 1 if n == candidate else -1\n    return candidate")

p("Intersection of Two Arrays","intersection-two-arrays","easy",["arrays","hash-table"],["Amazon","Google"],"Return the intersection of two arrays.",[{"input":"nums1=[1,2,2,1], nums2=[2,2]","output":"[2]","explanation":""}],"1 <= nums.length <= 1000",["Use sets"],[{"input":"4\n1 2 2 1\n2\n2 2","output":"2"},{"input":"4\n4 9 5\n9\n9 4 9 8 4","output":"4 9"}],[{"input":"1\n1\n1\n1","output":"1"}],"def intersection(nums1, nums2):\n    return list(set(nums1) & set(nums2))")

p("Rotate Array","rotate-array","easy",["arrays"],["Amazon","Google"],"Rotate array to the right by k steps.",[{"input":"nums=[1,2,3,4,5,6,7], k=3","output":"[5,6,7,1,2,3,4]","explanation":""}],"1 <= nums.length <= 10^5",["Reverse the array"],[{"input":"7\n1 2 3 4 5 6 7\n3","output":"5 6 7 1 2 3 4"},{"input":"4\n-1 -100 3 99\n2","output":"3 99 -1 -100"}],[{"input":"3\n1 2 3\n1","output":"3 1 2"}],"def rotate(nums, k):\n    k %= len(nums)\n    nums[:] = nums[-k:] + nums[:-k]")

p("Longest Common Prefix","longest-common-prefix","easy",["strings"],["Amazon","Google"],"Find the longest common prefix string among an array of strings.",[{"input":"strs = [flower,flow,flight]","output":"fl","explanation":""}],"1 <= strs.length <= 200",["Sort the array first"],[{"input":"3\nflower flow flight","output":"fl"},{"input":"3\ndog racecar car","output":""}],[{"input":"1\na","output":"a"}],"def longestCommonPrefix(strs):\n    if not strs: return ''\n    strs.sort()\n    first, last = strs[0], strs[-1]\n    i = 0\n    while i < len(first) and first[i] == last[i]: i += 1\n    return first[:i]")

p("Reverse Linked List","reverse-linked-list","easy",["linked-list"],["Amazon","Google","Microsoft"],"Reverse a singly linked list.",[{"input":"[1,2,3,4,5]","output":"[5,4,3,2,1]","explanation":""}],"1 <= n <= 5000",["Use three pointers"],[{"input":"5\n1 2 3 4 5","output":"5 4 3 2 1"},{"input":"2\n1 2","output":"2 1"}],[{"input":"1\n1","output":"1"}],"def reverseList(head):\n    prev = None\n    while head:\n        nxt = head.next\n        head.next = prev\n        prev = head\n        head = nxt\n    return prev")

p("Linked List Cycle","linked-list-cycle","easy",["linked-list","two-pointers"],["Amazon","Microsoft"],"Detect if a linked list has a cycle.",[{"input":"head = [3,2,0,-4], pos=1","output":"true","explanation":""}],"0 <= list.length <= 10^4",["Use Floyd's algorithm"],[{"input":"3\n3 2 0 -4\n1","output":"true"},{"input":"2\n1 2\n0","output":"true"}],[{"input":"1\n1\n-1","output":"false"}],"def hasCycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast: return True\n    return False")

p("Middle of the Linked List","middle-linked-list","easy",["linked-list","two-pointers"],["Amazon"],"Find the middle node of a linked list.",[{"input":"[1,2,3,4,5]","output":"3","explanation":""}],"1 <= n <= 100",["Use slow and fast pointers"],[{"input":"5\n1 2 3 4 5","output":"3"},{"input":"6\n1 2 3 4 5 6","output":"4"}],[{"input":"1\n1","output":"1"}],"def middleNode(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n    return slow")

p("Sqrt(x)","sqrtx","easy",["math","binary-search"],["Amazon","Microsoft"],"Compute the integer square root of x.",[{"input":"4","output":"2","explanation":""}],"0 <= x <= 2^31-1",["Use binary search"],[{"input":"4","output":"2"},{"input":"8","output":"2"}],[{"input":"0","output":"0"}],"def mySqrt(x):\n    lo, hi = 0, x\n    while lo <= hi:\n        mid = (lo+hi)//2\n        if mid*mid == x: return mid\n        elif mid*mid < x: lo = mid+1\n        else: hi = mid-1\n    return hi")

p("Add Binary","add-binary","easy",["strings","math"],["Amazon"],"Add two binary strings and return the result.",[{"input":"a=11, b=1010","output":"10000","explanation":""}],"1 <= a.length, b.length <= 10^4",["Use carry"],[{"input":"11\n1010","output":"10000"},{"input":"101\n101","output":"1010"}],[{"input":"0\n0","output":"0"}],"def addBinary(a, b):\n    return bin(int(a,2)+int(b,2))[2:]")

p("Number of 1 Bits","number-of-1-bits","easy",["bit-manipulation"],["Amazon"],"Count the number of 1 bits in the binary representation.",[{"input":"11","output":"3","explanation":""}],"The input must be a positive integer.",["Use bit manipulation"],[{"input":"11","output":"3"},{"input":"128","output":"1"}],[{"input":"2147483645","output":"30"}],"def hammingWeight(n):\n    count = 0\n    while n:\n        count += n & 1\n        n >>= 1\n    return count")

p("Reverse Bits","reverse-bits","easy",["bit-manipulation"],["Amazon"],"Reverse bits of a given 32 bits unsigned integer.",[{"input":"43261596","output":"964176192","explanation":""}],"The input must be a 32-bit unsigned integer.",["Process bit by bit"],[{"input":"43261596","output":"964176192"},{"input":"4294967293","output":"3221225471"}],[{"input":"0","output":"0"}],"def reverseBits(n):\n    result = 0\n    for _ in range(32):\n        result = (result << 1) | (n & 1)\n        n >>= 1\n    return result")

p("Happy Number","happy-number","easy",["math","hash-table"],["Amazon"],"Determine if a number is happy.",[{"input":"19","output":"true","explanation":""}],"1 <= n <= 2^31 - 1",["Use a set to detect cycles"],[{"input":"19","output":"true"},{"input":"2","output":"false"}],[{"input":"1","output":"true"}],"def isHappy(n):\n    seen = set()\n    while n != 1 and n not in seen:\n        seen.add(n)\n        n = sum(int(d)**2 for d in str(n))\n    return n == 1")

p("Ugly Number","ugly-number","easy",["math"],["Amazon"],"Determine if a number is ugly (only has factors 2, 3, 5).",[{"input":"6","output":"true","explanation":""}],"-2^31 <= n <= 2^31 - 1",["Keep dividing by 2, 3, 5"],[{"input":"6","output":"true"},{"input":"14","output":"false"}],[{"input":"1","output":"true"}],"def isUgly(n):\n    if n <= 0: return False\n    for p in [2,3,5]:\n        while n % p == 0: n //= p\n    return n == 1")

# === MEDIUM (40) ===
p("Longest Substring Without Repeating Characters","longest-substring-without-repeating","medium",["strings","sliding-window","hash-table"],["Amazon","Google","Meta"],"Find the length of the longest substring without repeating characters.",[{"input":"abcabcbb","output":"3","explanation":""}],"0 <= s.length <= 5*10^4",["Sliding window with hash set"],[{"input":"8\nabcabcbb","output":"3"},{"input":"5\nbbbbb","output":"1"}],[{"input":"6\npwwkew","output":"3"}],"def lengthOfLongestSubstring(s):\n    char_set = set()\n    l = max_len = 0\n    for r in range(len(s)):\n        while s[r] in char_set:\n            char_set.remove(s[l])\n            l += 1\n        char_set.add(s[r])\n        max_len = max(max_len, r-l+1)\n    return max_len")

p("3Sum","3sum","medium",["arrays","two-pointers","sorting"],["Amazon","Google","Meta"],"Find all unique triplets that sum to zero.",[{"input":"nums=[-1,0,1,2,-1,-4]","output":"[[-1,-1,2],[-1,0,1]]","explanation":""}],"3 <= nums.length <= 3000",["Sort and use two pointers"],[{"input":"6\n-1 0 1 2 -1 -4","output":"-1 0 1 -1 -1 2"},{"input":"3\n0 0 0","output":"0 0 0"}],[{"input":"3\n0 1 1","output":""}],"def threeSum(nums):\n    nums.sort()\n    result = []\n    for i in range(len(nums)-2):\n        if i > 0 and nums[i] == nums[i-1]: continue\n        lo, hi = i+1, len(nums)-1\n        while lo < hi:\n            s = nums[i]+nums[lo]+nums[hi]\n            if s < 0: lo += 1\n            elif s > 0: hi -= 1\n            else:\n                result.append([nums[i],nums[lo],nums[hi]])\n                while lo < hi and nums[lo]==nums[lo+1]: lo+=1\n                while lo < hi and nums[hi]==nums[hi-1]: hi-=1\n                lo+=1; hi-=1\n    return result",2000)

p("Container With Most Water","container-with-most-water","medium",["arrays","two-pointers"],["Amazon","Meta"],"Find two lines forming a container holding the most water.",[{"input":"height=[1,8,6,2,5,4,8,3,7]","output":"49","explanation":""}],"2 <= n <= 10^5",["Use two pointers from both ends"],[{"input":"9\n1 8 6 2 5 4 8 3 7","output":"49"},{"input":"2\n1 1","output":"1"}],[{"input":"3\n1 2 1","output":"2"}],"def maxArea(height):\n    lo, hi = 0, len(height)-1\n    mx = 0\n    while lo < hi:\n        mx = max(mx, min(height[lo],height[hi])*(hi-lo))\n        if height[lo] < height[hi]: lo += 1\n        else: hi -= 1\n    return mx")

p("Product of Array Except Self","product-of-array-except-self","medium",["arrays"],["Amazon","Google","Meta"],"Return array where each element is product of all other elements.",[{"input":"nums=[1,2,3,4]","output":"[24,12,8,6]","explanation":""}],"2 <= nums.length <= 10^5",["Use prefix and suffix products"],[{"input":"4\n1 2 3 4","output":"24 12 8 6"},{"input":"3\n-1 1 0","output":"0 0 0"}],[{"input":"2\n2 3","output":"3 2"}],"def productExceptSelf(nums):\n    n = len(nums)\n    result = [1]*n\n    prefix = 1\n    for i in range(n):\n        result[i] = prefix\n        prefix *= nums[i]\n    suffix = 1\n    for i in range(n-1,-1,-1):\n        result[i] *= suffix\n        suffix *= nums[i]\n    return result")

p("Find All Anagrams in a String","find-all-anagrams","medium",["strings","sliding-window","hash-table"],["Amazon","Meta"],"Find all start indices of p's anagrams in s.",[{"input":"s=cbaebabacd, p=abc","output":"[0,6]","explanation":""}],"1 <= s.length, p.length <= 3*10^4",["Sliding window with frequency count"],[{"input":"10\ncbaebabacd\n3\nabc","output":"0 6"},{"input":"7\nabab\n3\nab","output":"0 1 2"}],[{"input":"6\naabaab\n3\naba","output":"1"}],"from collections import Counter\ndef findAnagrams(s, p):\n    pc, sc = Counter(p), Counter()\n    res = []\n    for i, c in enumerate(s):\n        sc[c] += 1\n        if i >= len(p): sc[s[i-len(p)]] -= 1\n        if sc == pc: res.append(i-len(p)+1)\n    return res",2000)

p("Group Anagrams","group-anagrams","medium",["strings","hash-table","sorting"],["Amazon","Google"],"Group strings that are anagrams of each other.",[{"input":"strs=[eat,tea,tan,ate,nat,bat]","output":"[[eat,tea,ate],[tan,nat],[bat]]","explanation":""}],"1 <= strs.length <= 10^4",["Use sorted string as key"],[{"input":"3\nate eat tea","output":"ate eat tea"},{"input":"1\na","output":"a"}],[{"input":"2\nab ba","output":"ab ba"}],"from collections import defaultdict\ndef groupAnagrams(strs):\n    d = defaultdict(list)\n    for s in strs: d[tuple(sorted(s))].append(s)\n    return [v for v in d.values()]",2000)

p("Kth Largest Element in an Array","kth-largest-element","medium",["arrays","heap","sorting"],["Amazon","Meta"],"Find the kth largest element.",[{"input":"nums=[3,2,1,5,6,4], k=2","output":"5","explanation":""}],"1 <= k <= nums.length <= 10^5",["Use min-heap of size k"],[{"input":"6\n3 2 1 5 6 4\n2","output":"5"},{"input":"3\n3 2 3\n1","output":"3"}],[{"input":"1\n1\n1","output":"1"}],"import heapq\ndef findKthLargest(nums, k):\n    return heapq.nlargest(k, nums)[-1]")

p("Top K Frequent Elements","top-k-frequent-elements","medium",["arrays","hash-table","heap"],["Amazon","Meta","Google"],"Return the k most frequent elements.",[{"input":"nums=[1,1,1,2,2,3], k=2","output":"[1,2]","explanation":""}],"1 <= nums.length <= 10^5",["Count frequencies then use heap"],[{"input":"6\n1 1 1 2 2 3\n2","output":"1 2"},{"input":"1\n1\n1","output":"1"}],[{"input":"4\n4 1 -1 2\n2","output":"4 -1"}],"from collections import Counter\nimport heapq\ndef topKFrequent(nums, k):\n    return [x for x,_ in Counter(nums).most_common(k)]")

p("Subarray Sum Equals K","subarray-sum-equals-k","medium",["arrays","hash-table"],["Amazon","Google"],"Count contiguous subarrays whose sum equals k.",[{"input":"nums=[1,1,1], k=2","output":"2","explanation":""}],"1 <= nums.length <= 2*10^4",["Use prefix sum with hash map"],[{"input":"3\n1 1 1\n2","output":"2"},{"input":"3\n1 2 3\n3","output":"2"}],[{"input":"1\n0\n0","output":"1"}],"def subarraySum(nums, k):\n    count = prefix = 0\n    d = {0:1}\n    for n in nums:\n        prefix += n\n        count += d.get(prefix-k, 0)\n        d[prefix] = d.get(prefix, 0) + 1\n    return count")

p("Longest Common Subsequence","longest-common-subsequence","medium",["dynamic-programming","strings"],["Amazon","Google"],"Find length of longest common subsequence.",[{"input":"text1=abcde, text2=ace","output":"3","explanation":""}],"1 <= text1.length, text2.length <= 1000",["Use 2D DP table"],[{"input":"5\nabcde\n3\nace","output":"3"},{"input":"7\nabcdefg\n5\nacefg","output":"4"}],[{"input":"3\nabc\n3\ndef","output":"0"}],"def longestCommonSubsequence(text1, text2):\n    m, n = len(text1), len(text2)\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    for i in range(1,m+1):\n        for j in range(1,n+1):\n            if text1[i-1]==text2[j-1]: dp[i][j]=dp[i-1][j-1]+1\n            else: dp[i][j]=max(dp[i-1][j],dp[i][j-1])\n    return dp[m][n]",2000)

p("Coin Change","coin-change","medium",["dynamic-programming","arrays"],["Amazon","Microsoft"],"Find fewest coins needed to make up amount.",[{"input":"coins=[1,5,10,25], amount=30","output":"2","explanation":""}],"1 <= coins.length <= 12, 0 <= amount <= 10^4",["Bottom-up DP"],[{"input":"4\n1 5 10 25\n30","output":"2"},{"input":"3\n1 2 5\n11","output":"3"}],[{"input":"1\n2\n3","output":"-1"}],"def coinChange(coins, amount):\n    dp = [float('inf')]*(amount+1)\n    dp[0] = 0\n    for i in range(1, amount+1):\n        for c in coins:\n            if c <= i: dp[i] = min(dp[i], dp[i-c]+1)\n    return dp[amount] if dp[amount]!=float('inf') else -1",2000)

p("Word Break","word-break","medium",["dynamic-programming","strings","hash-table"],["Meta","Amazon"],"Determine if s can be segmented into dictionary words.",[{"input":"s=leetcode, wordDict=[leet,code]","output":"true","explanation":""}],"1 <= s.length <= 300",["DP where dp[i] = can segment s[:i]"],[{"input":"8\nleetcode\n2\nleet code","output":"true"},{"input":"7\ncatsandog\n5\ncats dog sand and cat","output":"false"}],[{"input":"3\nabc\n3\na b c","output":"true"}],"def wordBreak(s, wordDict):\n    words = set(wordDict)\n    dp = [False]*(len(s)+1)\n    dp[0] = True\n    for i in range(1,len(s)+1):\n        for j in range(i):\n            if dp[j] and s[j:i] in words:\n                dp[i] = True\n                break\n    return dp[-1]",2000)

p("Number of Islands","number-of-islands","medium",["graphs","dfs","bfs"],["Amazon","Google","Meta"],"Count the number of islands in a 2D grid.",[{"input":"grid=[[1,1,0],[1,0,0],[0,0,1]]","output":"2","explanation":""}],"m,n <= 300",["DFS/BFS to explore each island"],[{"input":"3 3\n1 1 0\n1 0 0\n0 0 1","output":"2"},{"input":"3 3\n1 1 1\n1 1 1\n1 1 1","output":"1"}],[{"input":"2 2\n1 1\n1 1","output":"1"}],"def numIslands(grid):\n    if not grid: return 0\n    count = 0\n    for i in range(len(grid)):\n        for j in range(len(grid[0])):\n            if grid[i][j]=='1':\n                dfs(grid,i,j)\n                count+=1\n    return count\ndef dfs(g,i,j):\n    if i<0 or j<0 or i>=len(g) or j>=len(g[0]) or g[i][j]!='1': return\n    g[i][j]='0'\n    dfs(g,i+1,j);dfs(g,i-1,j);dfs(g,i,j+1);dfs(g,i,j-1)",2000)

p("Course Schedule","course-schedule","medium",["graphs","topological-sort","bfs"],["Amazon","Google","Meta"],"Determine if you can finish all courses.",[{"input":"numCourses=2, prerequisites=[[1,0]]","output":"true","explanation":""}],"1 <= numCourses <= 2000",["Detect cycle using topological sort"],[{"input":"2\n1 0","output":"true"},{"input":"2\n1 0\n0 1","output":"false"}],[{"input":"3\n1 0\n2 1","output":"true"}],"from collections import defaultdict,deque\ndef canFinish(numCourses, prerequisites):\n    graph=defaultdict(list)\n    indeg=[0]*numCourses\n    for a,b in prerequisites:\n        graph[b].append(a); indeg[a]+=1\n    q=deque([i for i in range(numCourses) if indeg[i]==0])\n    count=0\n    while q:\n        node=q.popleft(); count+=1\n        for n in graph[node]:\n            indeg[n]-=1\n            if indeg[n]==0: q.append(n)\n    return count==numCourses",2000)

p("Implement Trie (Prefix Tree)","implement-trie","medium",["trees","design","hash-table"],["Amazon","Google","Microsoft"],"Implement a trie with insert, search, and startsWith.",[{"input":"insert apple, search apple, search app, startsWith app","output":"true, false, true","explanation":""}],"1 <= word.length <= 2000",["Each node has children map and is_end flag"],[{"input":"insert apple\nsearch apple\nsearch app\nstartsWith app","output":"true\nfalse\ntrue"},{"input":"insert cat\nsearch cat\nsearch dog","output":"true\nfalse"}],[{"input":"insert a\nstartsWith a\nsearch a","output":"true\ntrue"}],"class TrieNode:\n    def __init__(self):\n        self.children={}\n        self.is_end=False\nclass Trie:\n    def __init__(self):\n        self.root=TrieNode()\n    def insert(self,word):\n        node=self.root\n        for c in word:\n            if c not in node.children: node.children[c]=TrieNode()\n            node=node.children[c]\n        node.is_end=True\n    def search(self,word):\n        node=self.root\n        for c in word:\n            if c not in node.children: return False\n            node=node.children[c]\n        return node.is_end\n    def startsWith(self,prefix):\n        node=self.root\n        for c in prefix:\n            if c not in node.children: return False\n            node=node.children[c]\n        return True",2000)

p("Validate Binary Search Tree","validate-bst","medium",["trees","binary-search","dfs"],["Amazon","Google","Meta"],"Check if a binary tree is a valid BST.",[{"input":"[2,1,3]","output":"true","explanation":""}],"1 <= nodes <= 10^4",["Use range checking"],[{"input":"3\n2 1 3","output":"true"},{"input":"5\n5 1 4 null null 3 6","output":"false"}],[{"input":"1\n1","output":"true"}],"def isValidBST(root, lo=float('-inf'), hi=float('inf')):\n    if not root: return True\n    if root.val <= lo or root.val >= hi: return False\n    return isValidBST(root.left, lo, root.val) and isValidBST(root.right, root.val, hi)",2000)

p("Binary Tree Level Order Traversal","binary-tree-level-order","medium",["trees","bfs"],["Amazon","Google","Meta"],"Return level order traversal of a binary tree.",[{"input":"[3,9,20,null,null,15,7]","output":"[[3],[9,20],[15,7]]","explanation":""}],"0 <= nodes <= 2000",["Use BFS with queue"],[{"input":"3\n3 9 20","output":"3 9 20"},{"input":"1\n1","output":"1"}],[{"input":"0\nnull","output":""}],"from collections import deque\ndef levelOrder(root):\n    if not root: return []\n    result, queue = [], deque([root])\n    while queue:\n        level=[]\n        for _ in range(len(queue)):\n            node=queue.popleft()\n            level.append(node.val)\n            if node.left: queue.append(node.left)\n            if node.right: queue.append(node.right)\n        result.append(level)\n    return result",2000)

p("Lowest Common Ancestor of a Binary Tree","lowest-common-ancestor","medium",["trees","recursion"],["Amazon","Google","Meta"],"Find the lowest common ancestor of two nodes.",[{"input":"root=[3,5,1,6,2,0,8], p=5, q=1","output":"3","explanation":""}],"2 <= nodes <= 10^5",["Recursive approach"],[{"input":"5\n3 5 1 6 2\n5 1","output":"3"},{"input":"3\n1 2 3\n2 3","output":"1"}],[{"input":"2\n1 2\n1 2","output":"1"}],"def lowestCommonAncestor(root, p, q):\n    if not root or root==p or root==q: return root\n    left=lowestCommonAncestor(root.left,p,q)\n    right=lowestCommonAncestor(root.right,p,q)\n    if left and right: return root\n    return left or right",2000)

p("Clone Graph","clone-graph","medium",["graphs","dfs","bfs"],["Amazon","Meta"],"Clone an undirected graph.",[{"input":"adjList=[[2,4],[1,3],[2,4],[1,3]]","output":"[[2,4],[1,3],[2,4],[1,3]]","explanation":""}],"0 <= nodes <= 100",["Use DFS with hash map"],[{"input":"4\n2 4\n1 3\n2 4\n1 3","output":"cloned"},{"input":"1\nempty","output":"empty"}],[{"input":"0\nnull","output":"null"}],"def cloneGraph(node):\n    if not node: return None\n    visited={}\n    def dfs(n):\n        if n in visited: return visited[n]\n        copy=Node(n.val)\n        visited[n]=copy\n        for nb in n.neighbors:\n            copy.neighbors.append(dfs(nb))\n        return copy\n    return dfs(node)",2000)

p("Pacific Atlantic Water Flow","pacific-atlantic-water-flow","medium",["graphs","dfs","bfs"],["Amazon","Google"],"Find cells where water can flow to both pacific and atlantic oceans.",[{"input":"heights=[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]","output":"[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]","explanation":""}],"m,n <= 200",["DFS from both oceans"],[{"input":"2 2\n1 2\n3 4","output":"cells"},{"input":"1 1\n1","output":"0 0"}],[{"input":"1 1\n1","output":"0 0"}],"def pacificAtlantic(heights):\n    R,C=len(heights),len(heights[0])\n    def dfs(r,c,prev,visited):\n        if r<0 or c<0 or r>=R or c>=C or (r,c) in visited or heights[r][c]<prev: return\n        visited.add((r,c))\n        for dr,dc in [(0,1),(0,-1),(1,0),(-1,0)]:\n            dfs(r+dr,c+dc,heights[r][c],visited)\n    pac,atl=set(),set()\n    for r in range(R):\n        dfs(r,0,0,pac); dfs(r,C-1,0,atl)\n    for c in range(C):\n        dfs(0,c,0,pac); dfs(R-1,c,0,atl)\n    return [[r,c] for r,c in pac&atl]",2000)

p("Longest Increasing Subsequence","longest-increasing-subsequence","medium",["dynamic-programming","binary-search"],["Amazon","Google"],"Find length of the longest strictly increasing subsequence.",[{"input":"nums=[10,9,2,5,3,7,101,18]","output":"4","explanation":""}],"1 <= nums.length <= 2500",["DP or patience sorting"],[{"input":"9\n10 9 2 5 3 7 101 18","output":"4"},{"input":"4\n0 1 0 3 2 3","output":"4"}],[{"input":"1\n0","output":"1"}],"def lengthOfLIS(nums):\n    from bisect import bisect_left\n    tails=[]\n    for n in nums:\n        pos=bisect_left(tails,n)\n        if pos==len(tails): tails.append(n)\n        else: tails[pos]=n\n    return len(tails)",2000)

p("Decode Ways","decode-ways","medium",["dynamic-programming","strings"],["Amazon","Google"],"Count ways to decode a string of digits.",[{"input":"12","output":"2","explanation":""}],"1 <= s.length <= 100",["DP counting valid one and two digit codes"],[{"input":"2\n12","output":"2"},{"input":"3\n226","output":"3"}],[{"input":"5\n22619","output":"5"}],"def numDecodings(s):\n    if s[0]=='0': return 0\n    n=len(s)\n    dp=[0]*(n+1)\n    dp[0]=dp[1]=1\n    for i in range(2,n+1):\n        if s[i-1]!='0': dp[i]+=dp[i-1]\n        if 10<=int(s[i-2:i])<=26: dp[i]+=dp[i-2]\n    return dp[n]",2000)

p("Unique Paths","unique-paths","medium",["dynamic-programming","math"],["Amazon","Google"],"Count unique paths in a grid from top-left to bottom-right.",[{"input":"m=3, n=7","output":"28","explanation":""}],"1 <= m,n <= 100",["Use combinatorics or DP"],[{"input":"3\n7","output":"28"},{"input":"3\n2","output":"3"}],[{"input":"1\n1","output":"1"}],"def uniquePaths(m, n):\n    dp=[[1]*n for _ in range(m)]\n    for i in range(1,m):\n        for j in range(1,n):\n            dp[i][j]=dp[i-1][j]+dp[i][j-1]\n    return dp[m-1][n-1]",2000)

p("Minimum Path Sum","minimum-path-sum","medium",["dynamic-programming","arrays"],["Amazon","Google"],"Find minimum path sum from top-left to bottom-right.",[{"input":"grid=[[1,3,1],[1,5,1],[4,2,1]]","output":"7","explanation":""}],"m,n <= 200",["Use DP"],[{"input":"3 3\n1 3 1\n1 5 1\n4 2 1","output":"7"},{"input":"2 3\n1 2 3\n1 1 1","output":"3"}],[{"input":"1 1\n1","output":"1"}],"def minPathSum(grid):\n    m,n=len(grid),len(grid[0])\n    for i in range(m):\n        for j in range(n):\n            if i==0 and j==0: continue\n            elif i==0: grid[i][j]+=grid[i][j-1]\n            elif j==0: grid[i][j]+=grid[i-1][j]\n            else: grid[i][j]+=min(grid[i-1][j],grid[i][j-1])\n    return grid[m-1][n-1]",2000)

p("Search in Rotated Sorted Array","search-rotated-sorted-array","medium",["arrays","binary-search"],["Amazon","Google","Meta"],"Search for target in rotated sorted array.",[{"input":"nums=[4,5,6,7,0,1,2], target=0","output":"4","explanation":""}],"1 <= nums.length <= 5000",["Modified binary search"],[{"input":"7\n4 5 6 7 0 1 2\n0","output":"4"},{"input":"7\n4 5 6 7 0 1 2\n3","output":"-1"}],[{"input":"1\n0\n0","output":"0"}],"def search(nums, target):\n    lo,hi=0,len(nums)-1\n    while lo<=hi:\n        mid=(lo+hi)//2\n        if nums[mid]==target: return mid\n        if nums[lo]<=nums[mid]:\n            if nums[lo]<=target<nums[mid]: hi=mid-1\n            else: lo=mid+1\n        else:\n            if nums[mid]<target<=nums[hi]: lo=mid+1\n            else: hi=mid-1\n    return -1",2000)

p("Jump Game","jump-game","medium",["arrays","dynamic-programming","greedy"],["Amazon","Google"],"Determine if you can reach the last index.",[{"input":"nums=[2,3,1,1,4]","output":"true","explanation":""}],"1 <= nums.length <= 10^4",["Track the maximum reachable index"],[{"input":"5\n2 3 1 1 4","output":"true"},{"input":"5\n3 2 1 0 4","output":"false"}],[{"input":"1\n0","output":"true"}],"def canJump(nums):\n    max_reach=0\n    for i,n in enumerate(nums):\n        if i>max_reach: return False\n        max_reach=max(max_reach,i+n)\n    return True")

p("Gas Station","gas-station","medium",["arrays","greedy"],["Amazon","Google"],"Find the starting gas station to complete a circular tour.",[{"input":"gas=[1,2,3,4,5], cost=[3,4,5,1,2]","output":"3","explanation":""}],"n == gas.length",["If total gas >= total cost, solution exists"],[{"input":"5\n1 2 3 4 5\n3 4 5 1 2","output":"3"},{"input":"3\n2 3 4\n3 4 3","output":"-1"}],[{"input":"1\n2\n1","output":"0"}],"def canCompleteCircuit(gas, cost):\n    if sum(gas)<sum(cost): return -1\n    total=curr=0\n    for i in range(len(gas)):\n        curr+=gas[i]-cost[i]\n        if curr<0: total=i+1; curr=0\n    return total",2000)

p("Task Scheduler","task-scheduler","medium",["arrays","hash-table","greedy","heap"],["Meta","Amazon","Microsoft"],"Find least intervals to finish all tasks.",[{"input":"tasks=[A,A,A,B,B,B], n=2","output":"8","explanation":""}],"1 <= tasks.length <= 10^4",["The answer depends on the most frequent task"],[{"input":"6\nA A A B B B\n2","output":"8"},{"input":"4\nA A A A\n2","output":"10"}],[{"input":"3\nA B A\n2","output":"4"}],"from collections import Counter\ndef leastInterval(tasks, n):\n    freq=Counter(tasks)\n    mx=max(freq.values())\n    mx_cnt=sum(1 for v in freq.values() if v==mx)\n    return max(len(tasks),(mx-1)*(n+1)+mx_cnt)")

p("Reorganize String","reorganize-string","medium",["strings","hash-table","greedy","heap"],["Amazon","Google"],"Rearrange string so no two adjacent characters are the same.",[{"input":"aab","output":"aba","explanation":""}],"1 <= s.length <= 500",["Use greedy with max heap"],[{"input":"3\naab","output":"aba"},{"input":"3\naaab","output":""}],[{"input":"1\na","output":"a"}],"from collections import Counter\nimport heapq\ndef reorganizeString(s):\n    cnt=Counter(s)\n    if max(cnt.values())>(len(s)+1)//2: return ''\n    heap=[(-v,k) for k,v in cnt.items()]\n    heapq.heapify(heap)\n    res=[]\n    while len(heap)>=2:\n        v1,k1=heapq.heappop(heap)\n        v2,k2=heapq.heappop(heap)\n        res.extend([k1,k2])\n        if v1+1: heapq.heappush(heap,(v1+1,k1))\n        if v2+1: heapq.heappush(heap,(v2+1,k2))\n    if heap: res.append(heapq.heappop(heap)[1])\n    return ''.join(res)")

p("Non-overlapping Intervals","non-overlapping-intervals","medium",["arrays","greedy","sorting"],["Amazon","Google"],"Find minimum number of intervals to remove to make rest non-overlapping.",[{"input":"intervals=[[1,2],[2,3],[3,4],[1,3]]","output":"1","explanation":""}],"1 <= intervals.length <= 10^4",["Sort by end time, greedily pick non-overlapping"],[{"input":"4\n1 2\n2 3\n3 4\n1 3","output":"1"},{"input":"3\n1 2\n1 2\n1 2","output":"2"}],[{"input":"2\n1 2\n2 3","output":"0"}],"def eraseOverlapIntervals(intervals):\n    intervals.sort(key=lambda x:x[1])\n    count=0\n    end=float('-inf')\n    for s,e in intervals:\n        if s>=end: end=e\n        else: count+=1\n    return count")

p("Meeting Rooms II","meeting-rooms-ii","medium",["arrays","greedy","heap","sorting"],["Amazon","Google","Meta"],"Find minimum number of conference rooms required.",[{"input":"intervals=[[0,30],[5,10],[15,20]]","output":"2","explanation":""}],"1 <= intervals.length <= 10^4",["Use a min heap to track end times"],[{"input":"3\n0 30\n5 10\n15 20","output":"2"},{"input":"2\n7 10\n2 4","output":"1"}],[{"input":"1\n0 1","output":"1"}],"import heapq\ndef minMeetingRooms(intervals):\n    intervals.sort()\n    heap=[]\n    for s,e in intervals:\n        if heap and heap[0]<=s: heapq.heapreplace(heap,e)\n        else: heapq.heappush(heap,e)\n    return len(heap)")

p("Graph Valid Tree","graph-valid-tree","medium",["graphs","union-find","dfs"],["Amazon","Google"],"Check if n nodes form a valid tree.",[{"input":"n=5, edges=[[0,1],[0,2],[0,3],[1,4]]","output":"true","explanation":""}],"1 <= n <= 2000",["A tree has n-1 edges and is connected"],[{"input":"5\n0 1\n0 2\n0 3\n1 4","output":"true"},{"input":"5\n0 1\n1 2\n2 3\n1 3","output":"false"}],[{"input":"1\nnull","output":"true"}],"def validTree(n, edges):\n    if len(edges)!=n-1: return False\n    parent=list(range(n))\n    def find(x):\n        while parent[x]!=x:\n            parent[x]=parent[parent[x]]\n            x=parent[x]\n        return x\n    for a,b in edges:\n        ra,rb=find(a),find(b)\n        if ra==rb: return False\n        parent[ra]=rb\n    return True")

p("Number of Provinces","number-of-provinces","medium",["graphs","dfs","union-find"],["Amazon","Google"],"Find number of connected components.",[{"input":"isConnected=[[1,1,0],[1,1,0],[0,0,1]]","output":"2","explanation":""}],"1 <= n <= 200",["DFS from each unvisited node"],[{"input":"3\n1 1 0\n1 1 0\n0 0 1","output":"2"},{"input":"3\n1 0 0\n0 1 0\n0 0 1","output":"3"}],[{"input":"1\n1","output":"1"}],"def findCircleNum(isConnected):\n    n=len(isConnected)\n    visited=set()\n    def dfs(i):\n        for j in range(n):\n            if isConnected[i][j] and j not in visited:\n                visited.add(j)\n                dfs(j)\n    count=0\n    for i in range(n):\n        if i not in visited:\n            visited.add(i)\n            dfs(i)\n            count+=1\n    return count",2000)

# === HARD (25) ===
p("Median of Two Sorted Arrays","median-two-sorted-arrays","hard",["arrays","binary-search"],["Google","Amazon","Microsoft"],"Find the median of two sorted arrays in O(log(m+n)).",[{"input":"nums1=[1,3], nums2=[2]","output":"2.0","explanation":""}],"nums1.length == m, nums2.length == n","Binary search on the smaller array",[{"input":"2\n1 3\n1\n2","output":"2.0"},{"input":"2\n1 2\n2\n3 4","output":"2.5"}],[{"input":"1\n2\n1\n1","output":"1.0"}],"def findMedianSortedArrays(a,b):\n    if len(a)>len(b): a,b=b,a\n    m,n=len(a),len(b)\n    lo,hi=0,m\n    while lo<=hi:\n        i=(lo+hi)//2\n        j=(m+n+1)//2-i\n        left=a[i-1] if i>0 else float('-inf')\n        right=a[i] if i<m else float('inf')\n        leftb=b[j-1] if j>0 else float('-inf')\n        rightb=b[j] if j<n else float('inf')\n        if left<=rightb and leftb<=right:\n            if(m+n)%2==1: return max(left,leftb)\n            return(max(left,leftb)+min(right,rightb))/2\n        elif left>rightb: hi=i-1\n        else: lo=i+1",2000)

p("Trapping Rain Water","trapping-rain-water","hard",["arrays","two-pointers","stack"],["Amazon","Google"],"Compute how much water can be trapped.",[{"input":"height=[0,1,0,2,1,0,1,3,2,1,2,1]","output":"6","explanation":""}],"1 <= height.length <= 2*10^4",["Use two pointers to track left and right max"],[{"input":"12\n0 1 0 2 1 0 1 3 2 1 2 1","output":"6"},{"input":"6\n4 2 0 3 2 5","output":"9"}],[{"input":"3\n1 0 1","output":"1"}],"def trap(height):\n    if not height: return 0\n    l,r=0,len(height)-1\n    l_max=r_max=ans=0\n    while l<r:\n        l_max=max(l_max,height[l])\n        r_max=max(r_max,height[r])\n        if l_max<r_max:\n            ans+=l_max-height[l]; l+=1\n        else:\n            ans+=r_max-height[r]; r-=1\n    return ans",2000)

p("LRU Cache","lru-cache","hard",["hash-table","linked-list","design"],["Amazon","Google","Meta","Microsoft"],"Design a Least Recently Used cache.",[{"input":"LRUCache(2), put(1,1), put(2,2), get(1), put(3,3), get(2)","output":"1, -1","explanation":""}],"1 <= capacity <= 3000",["Hash map + doubly linked list"],[{"input":"2\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2","output":"1\n-1"}],[{"input":"1\nput 1 1\nput 2 2\nget 1","output":"-1"}],"from collections import OrderedDict\nclass LRUCache:\n    def __init__(self,cap):\n        self.cache=OrderedDict()\n        self.cap=cap\n    def get(self,key):\n        if key not in self.cache: return -1\n        self.cache.move_to_end(key)\n        return self.cache[key]\n    def put(self,key,value):\n        if key in self.cache: self.cache.move_to_end(key)\n        self.cache[key]=value\n        if len(self.cache)>self.cap: self.cache.popitem(last=False)",2000)

p("Serialize and Deserialize Binary Tree","serialize-deserialize-binary-tree","hard",["trees","design","bfs"],["Amazon","Google","Meta","Microsoft"],"Design an algorithm to serialize and deserialize a binary tree.",[{"input":"root=[1,2,3,null,null,4,5]","output":"[1,2,3,null,null,4,5]","explanation":""}],"0 <= nodes <= 10^4",["Pre-order traversal works well"],[{"input":"5\n1 2 3 null null 4 5","output":"1 2 3 null null 4 5"},{"input":"1\n1","output":"1"}],[{"input":"0\nnull","output":"null"}],"class Codec:\n    def serialize(self,root):\n        if not root: return 'null'\n        return f'{root.val},{self.serialize(root.left)},{self.serialize(root.right)}'\n    def deserialize(self,data):\n        def helper(it):\n            val=next(it)\n            if val=='null': return None\n            node=TreeNode(int(val))\n            node.left=helper(it)\n            node.right=helper(it)\n            return node\n        return helper(iter(data.split(',')))",2000)

p("Word Ladder","word-ladder","hard",["graphs","bfs","strings"],["Amazon","Google","Meta"],"Find length of shortest transformation sequence from beginWord to endWord.",[{"input":"beginWord=hhit, endWord=cog, wordList=[hot,dog,lot,log,cog]","output":"5","explanation":""}],"1 <= beginWord.length <= 10",["BFS level by level"],[{"input":"hit\ncog\nhot dot dog lot log cog","output":"5"},{"input":"hit\ncog\nhot dot dog lot log","output":"0"}],[{"input":"a\nc\na b c","output":"2"}],"from collections import deque\ndef ladderLength(beginWord, endWord, wordList):\n    wordList=set(wordList)\n    if endWord not in wordList: return 0\n    queue=deque([(beginWord,1)])\n    while queue:\n        word,steps=queue.popleft()\n        for i in range(len(word)):\n            for c in 'abcdefghijklmnopqrstuvwxyz':\n                nw=word[:i]+c+word[i+1:]\n                if nw==endWord: return steps+1\n                if nw in wordList:\n                    wordList.remove(nw)\n                    queue.append((nw,steps+1))\n    return 0",2000)

p("Minimum Window Substring","minimum-window-substring","hard",["strings","sliding-window","hash-table"],["Amazon","Google","Meta"],"Find minimum window in s that contains all characters of t.",[{"input":"s=ADOBECODEBANC, t=ABC","output":"BANC","explanation":""}],"m,n <= 10^5",["Sliding window with frequency map"],[{"input":"12\nADOBECODEBANC\n3\nABC","output":"BANC"},{"input":"7\na a a b c b a","output":"b a"}],[{"input":"1\na\n1\na","output":"a"}],"def minWindow(s,t):\n    from collections import Counter\n    need=Counter(t)\n    missing=len(t)\n    start=0,end=0,min_start=0,min_len=float('inf')\n    for end,c in enumerate(s):\n        if need[c]>0: missing-=1\n        need[c]-=1\n        while missing==0:\n            if end-start+1<min_len:\n                min_len=end-start+1\n                min_start=start\n            need[s[start]]+=1\n            if need[s[start]]>0: missing+=1\n            start+=1\n    return '' if min_len==float('inf') else s[min_start:min_start+min_len]",2000)

p("Sliding Window Maximum","sliding-window-maximum","hard",["arrays","queue","heap"],["Amazon","Google","Meta"],"Find the maximum value in each sliding window of size k.",[{"input":"nums=[1,3,-1,-3,5,3,6,7], k=3","output":"[3,3,5,5,6,7]","explanation":""}],"1 <= nums.length <= 10^5",["Use a monotonic deque"],[{"input":"8\n1 3 -1 -3 5 3 6 7\n3","output":"3 3 5 5 6 7"},{"input":"1\n1\n1","output":"1"}],[{"input":"3\n1 -1\n1","output":"1 -1"}],"from collections import deque\ndef maxSlidingWindow(nums, k):\n    dq=deque()\n    result=[]\n    for i in range(len(nums)):\n        while dq and dq[0]<i-k+1: dq.popleft()\n        while dq and nums[dq[-1]]<nums[i]: dq.pop()\n        dq.append(i)\n        if i>=k-1: result.append(nums[dq[0]])\n    return result",2000)

p("Merge k Sorted Lists","merge-k-sorted-lists","hard",["linked-list","heap","divide-and-conquer"],["Amazon","Google","Meta"],"Merge k sorted linked lists into one sorted list.",[{"input":"lists=[[1,4,5],[1,3,4],[2,6]]","output":"[1,1,2,3,4,4,5,6]","explanation":""}],"k == lists.length",["Use a min heap"],[{"input":"3\n1 4 5\n1 3 4\n2 6","output":"1 1 2 3 4 4 5 6"},{"input":"0\nnull","output":""}],[{"input":"1\n0","output":"0"}],"import heapq\ndef mergeKLists(lists):\n    heap=[]\n    for i,l in enumerate(lists):\n        if l: heapq.heappush(heap,(l.val,i,l))\n    dummy=curr=ListNode(0)\n    while heap:\n        val,i,node=heapq.heappop(heap)\n        curr.next=node\n        curr=curr.next\n        if node.next:\n            heapq.heappush(heap,(node.next.val,i,node.next))\n    return dummy.next",2000)

p("Find Median from Data Stream","find-median-data-stream","hard",["heap","design","sorting"],["Amazon","Google","Meta"],"Design a data structure to add numbers and find median.",[{"input":"addNum(1), findMedian(), addNum(2), findMedian()","output":"1, 1.5","explanation":""}],"At most 5*10^4 calls",["Use two heaps"],[{"input":"add 1\nmedian\nadd 2\nmedian","output":"1\n1.5"}],[{"input":"add 5\nmedian","output":"5"}],"import heapq\nclass MedianFinder:\n    def __init__(self):\n        self.lo=[]; self.hi=[]\n    def addNum(self,num):\n        heapq.heappush(self.lo,-num)\n        heapq.heappush(self.hi,-heapq.heappop(self.lo))\n        if len(self.hi)>len(self.lo):\n            heapq.heappush(self.lo,-heapq.heappop(self.hi))\n    def findMedian(self):\n        if len(self.lo)>len(self.hi): return -self.lo[0]\n        return(-self.lo[0]+self.hi[0])/2",2000)

p("Edit Distance","edit-distance","hard",["dynamic-programming","strings"],["Amazon","Google"],"Find minimum operations to convert word1 to word2.",[{"input":"word1=horse, word2=ros","output":"3","explanation":""}],"0 <= word1.length, word2.length <= 500",["2D DP table"],[{"input":"5\nhorse\n3\nros","output":"3"},{"input":"5\nintention\n9\nexecution","output":"5"}],[{"input":"1\na\n1\na","output":"0"}],"def minDistance(word1, word2):\n    m,n=len(word1),len(word2)\n    dp=[[0]*(n+1) for _ in range(m+1)]\n    for i in range(m+1): dp[i][0]=i\n    for j in range(n+1): dp[0][j]=j\n    for i in range(1,m+1):\n        for j in range(1,n+1):\n            if word1[i-1]==word2[j-1]: dp[i][j]=dp[i-1][j-1]\n            else: dp[i][j]=1+min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1])\n    return dp[m][n]",2000)

p("Regular Expression Matching","regex-matching","hard",["dynamic-programming","strings","recursion"],["Amazon","Google"],"Implement regular expression matching with . and *.",[{"input":"s=aa, p=a","output":"false","explanation":""}],"1 <= s.length, p.length <= 20",["2D DP"],[{"input":"2\naa\n1\na","output":"false"},{"input":"2\naa\n2\na*","output":"true"}],[{"input":"1\na\n1\n.","output":"true"}],"def isMatch(s,p):\n    m,n=len(s),len(p)\n    dp=[[False]*(n+1) for _ in range(m+1)]\n    dp[0][0]=True\n    for j in range(2,n+1):\n        if p[j-1]=='*': dp[0][j]=dp[0][j-2]\n    for i in range(1,m+1):\n        for j in range(1,n+1):\n            if p[j-1]=='*':\n                dp[i][j]=dp[i][j-2]\n                if p[j-2]==s[i-1] or p[j-2]=='.':\n                    dp[i][j]=dp[i][j] or dp[i-1][j]\n            elif p[j-1]=='.' or p[j-1]==s[i-1]:\n                dp[i][j]=dp[i-1][j-1]\n    return dp[m][n]",2000)

p("Longest Valid Parentheses","longest-valid-parentheses","hard",["strings","stack","dynamic-programming"],["Amazon","Google","Meta"],"Find length of the longest valid parentheses substring.",[{"input":"()(()","output":"2","explanation":""}],"0 <= s.length <= 3*10^4",["Use stack to track indices"],[{"input":"5\n()((","output":"2"},{"input":"6\n)()())","output":"4"}],[{"input":"2\n()","output":"2"}],"def longestValidParentheses(s):\n    stack=[-1]\n    max_len=0\n    for i,c in enumerate(s):\n        if c=='(': stack.append(i)\n        else:\n            stack.pop()\n            if not stack: stack.append(i)\n            else: max_len=max(max_len,i-stack[-1])\n    return max_len",2000)

p("N-Queens","n-queens","hard",["backtracking","arrays"],["Amazon","Google","Meta"],"Place n queens on n x n chessboard so no two attack each other.",[{"input":"4","output":"[['.Q..','...Q','Q...','..Q.'],['..Q.','Q...','...Q','.Q..']]","explanation":""}],"1 <= n <= 9",["Backtracking with sets for columns, diagonals"],[{"input":"4","output":"2 solutions"},{"input":"1","output":"1 solution"}],[{"input":"1","output":"1"}],"def solveNQueens(n):\n    result=[]\n    def backtrack(queens,xy_diff,xy_sum):\n        if len(queens)==n: result.append(['.'*(q)+'Q'+'.'*(n-q-1) for q in queens])\n        for q in range(n):\n            if q not in queens and len(queens)-q not in xy_diff and len(queens)+q not in xy_sum:\n                backtrack(queens+[q],xy_diff+[len(queens)-q],xy_sum+[len(queens)+q])\n    backtrack([],[],[])\n    return result",2000)

p("Burst Balloons","burst-balloons","hard",["dynamic-programming","arrays"],["Amazon","Google"],"Find maximum coins by bursting balloons optimally.",[{"input":"nums=[3,1,5,8]","output":"167","explanation":""}],"1 <= nums.length <= 300",["Interval DP"],[{"input":"4\n3 1 5 8","output":"167"},{"input":"1\n1","output":"1"}],[{"input":"3\n1 5 8","output":"167"}],"def maxCoins(nums):\n    nums=[1]+nums+[1]\n    n=len(nums)\n    dp=[[0]*n for _ in range(n)]\n    for l in range(n-2,0,-1):\n        for r in range(l,n-1):\n            for k in range(l,r+1):\n                dp[l][r]=max(dp[l][r],dp[l][k-1]+dp[k+1][r]+nums[l-1]*nums[k]*nums[r+1])\n    return dp[1][n-2]",2000)

p("Largest Rectangle in Histogram","largest-rectangle-histogram","hard",["stack","arrays"],["Amazon","Google","Meta"],"Find area of largest rectangle in histogram.",[{"input":"heights=[2,1,5,6,2,3]","output":"10","explanation":""}],"1 <= heights.length <= 10^5",["Use stack to track increasing heights"],[{"input":"6\n2 1 5 6 2 3","output":"10"},{"input":"3\n2 4","output":"8"}],[{"input":"1\n1","output":"1"}],"def largestRectangleArea(heights):\n    stack=[]\n    max_area=0\n    heights.append(0)\n    for i,h in enumerate(heights):\n        while stack and heights[stack[-1]]>h:\n            ht=heights[stack.pop()]\n            width=i if not stack else i-stack[-1]-1\n            max_area=max(max_area,ht*width)\n        stack.append(i)\n    return max_area",2000)

p("Candy","candy","hard",["arrays","greedy"],["Amazon","Google"],"Distribute candies so children with higher ratings get more candies.",[{"input":"ratings=[1,0,2]","output":"5","explanation":""}],"1 <= ratings.length <= 2*10^4",["Two passes: left to right, right to left"],[{"input":"3\n1 0 2","output":"5"},{"input":"4\n1 2 2","output":"7"}],[{"input":"1\n1","output":"1"}],"def candy(ratings):\n    n=len(ratings)\n    candies=[1]*n\n    for i in range(1,n):\n        if ratings[i]>ratings[i-1]: candies[i]=candies[i-1]+1\n    for i in range(n-2,-1,-1):\n        if ratings[i]>ratings[i+1]: candies[i]=max(candies[i],candies[i+1]+1)\n    return sum(candies)",2000)

p("Russian Doll Envelopes","russian-doll-envelopes","hard",["arrays","binary-search","dynamic-programming"],["Amazon","Google"],"Find maximum number of envelopes you can Russian doll.",[{"input":"envelopes=[[5,4],[6,4],[6,7],[2,3]]","output":"3","explanation":""}],"1 <= envelopes.length <= 10^5",["Sort and use LIS on heights"],[{"input":"4\n5 4\n6 4\n6 7\n2 3","output":"3"},{"input":"2\n1 1\n2 2","output":"2"}],[{"input":"1\n1 1","output":"1"}],"def maxEnvelopes(envelopes):\n    from bisect import bisect_left\n    envelopes.sort(key=lambda x:(x[0],-x[1]))\n    tails=[]\n    for _,h in envelopes:\n        pos=bisect_left(tails,h)\n        if pos==len(tails): tails.append(h)\n        else: tails[pos]=h\n    return len(tails)",2000)

p("Wildcard Matching","wildcard-matching","hard",["dynamic-programming","strings","greedy"],["Amazon","Google"],"Implement wildcard pattern matching with ? and *.",[{"input":"s=aa, p=a","output":"false","explanation":""}],"0 <= s.length, p.length <= 2000",["2D DP"],[{"input":"2\naa\n1\na","output":"false"},{"input":"2\naa\n2\n*","output":"true"}],[{"input":"1\na\n1\n?","output":"true"}],"def isMatch(s,p):\n    m,n=len(s),len(p)\n    dp=[[False]*(n+1) for _ in range(m+1)]\n    dp[0][0]=True\n    for j in range(1,n+1):\n        if p[j-1]=='*': dp[0][j]=dp[0][j-1]\n    for i in range(1,m+1):\n        for j in range(1,n+1):\n            if p[j-1]=='*': dp[i][j]=dp[i-1][j] or dp[i][j-1]\n            elif p[j-1]=='?' or p[j-1]==s[i-1]: dp[i][j]=dp[i-1][j-1]\n    return dp[m][n]",2000)

p("Maximal Rectangle","maximal-rectangle","hard",["stack","arrays","dynamic-programming"],["Amazon","Google"],"Find the largest rectangle containing only 1s in a binary matrix.",[{"input":"matrix=[[1,0,1,0,0],[1,0,1,1,1],[1,1,1,1,1],[1,0,0,1,0]]","output":"6","explanation":""}],"m,n <= 200",["Use histogram approach row by row"],[{"input":"4 5\n1 0 1 0 0\n1 0 1 1 1\n1 1 1 1 1\n1 0 0 1 0","output":"6"},{"input":"1 1\n1 1","output":"4"}],[{"input":"1 1\n1","output":"1"}],"def maximalRectangle(matrix):\n    if not matrix: return 0\n    n=len(matrix[0])\n    heights=[0]*(n+1)\n    max_area=0\n    for row in matrix:\n        for i in range(n): heights[i]=heights[i]+1 if row[i]=='1' else 0\n        stack=[]\n        for i in range(n+1):\n            while stack and heights[stack[-1]]>heights[i]:\n                ht=heights[stack.pop()]\n                w=i if not stack else i-stack[-1]-1\n                max_area=max(max_area,ht*w)\n            stack.append(i)\n    return max_area",2000)

p("Sudoku Solver","sudoku-solver","hard",["backtracking","arrays"],["Amazon","Google"],"Solve a Sudoku puzzle by filling empty cells.",[{"input":"board=[['5','3','.','.','7','.','.','.','.'],['6','.','.','1','9','5','.','.','.'],['.','9','8','.','.','.','.','6','.'],['8','.','.','.','6','.','.','.','3'],['4','.','.','8','.','3','.','.','1'],['7','.','.','.','2','.','.','.','6'],['.','6','.','.','.','.','2','8','.'],['.','.','.','4','1','9','.','.','5'],['.','.','.','.','8','.','.','7','9']]","output":"solved board","explanation":""}],"Board is 9x9",["Backtracking with constraint checking"],[{"input":"9x9 board","output":"solved"},{"input":"easy puzzle","output":"solved"}],[{"input":"valid board","output":"solved"}],"def solveSudoku(board):\n    def isValid(r,c,ch):\n        for i in range(9):\n            if board[r][i]==ch: return False\n            if board[i][c]==ch: return False\n            br,c=r//3*3+i//3,c//3*3+i%3\n            if board[br][cc]==ch: return False\n        return True\n    def solve(board):\n        for i in range(9):\n            for j in range(9):\n                if board[i][j]=='.':\n                    for ch in '123456789':\n                        if isValid(i,j,ch):\n                            board[i][j]=ch\n                            if solve(board): return True\n                            board[i][j]='.'\n                    return False\n        return True\n    solve(board)",2000)

p("Robot Room Cleaner","robot-room-cleaner","hard",["backtracking","design"],["Google"],"Clean an entire room using a robot with limited API.",[{"input":"robot API available","output":"room cleaned","explanation":""}],"m,n <= 100",["DFS with direction tracking"],[{"input":"room grid","output":"cleaned"},{"input":"simple room","output":"cleaned"}],[{"input":"1x1 room","output":"cleaned"}],"def cleanRoom(robot):\n    directions=[(0,1),(1,0),(0,-1),(-1,0)]\n    visited=set()\n    def goBack():\n        robot.turnRight()\n        robot.turnRight()\n        robot.move()\n        robot.turnRight()\n        robot.turnRight()\n    def dfs(r,c,d):\n        visited.add((r,c))\n        robot.clean()\n        for i in range(4):\n            nd=(d+i)%4\n            dr,dc=directions[nd]\n            nr,nc=r+dr,c+dc\n            if (nr,nc) not in visited and robot.move():\n                dfs(nr,nc,nd)\n                goBack()\n        robot.turnRight()\n        robot.turnRight()\n    dfs(0,0,0)",2000)

# === Additional EASY (2) ===
p("Plus One","plus-one","easy",["arrays","math"],["Amazon","Google"],"Increment a large integer represented as an array of digits.",[{"input":"digits=[1,2,3]","output":"[1,2,4]","explanation":""}],"1 <= digits.length <= 100",["Handle carry from right to left"],[{"input":"3\n1 2 3","output":"1 2 4"},{"input":"1\n9","output":"1 0"}],[{"input":"4\n9 9 9 9","output":"1 0 0 0 0"}],"def plusOne(digits):\n    for i in range(len(digits)-1,-1,-1):\n        if digits[i]<9: digits[i]+=1; return digits\n        digits[i]=0\n    return [1]+digits")

p("Merge Sorted Array","merge-sorted-array","easy",["arrays","two-pointers"],["Amazon","Google","Microsoft"],"Merge nums2 into nums1 in-place.",[{"input":"nums1=[1,2,3,0,0,0], m=3, nums2=[2,5,6], n=3","output":"[1,2,2,3,5,6]","explanation":""}],"0 <= m,n <= 200",["Merge from the end"],[{"input":"6\n1 2 3 0 0 0\n3\n2 5 6","output":"1 2 2 3 5 6"},{"input":"1\n0\n1\n1","output":"1"}],[{"input":"2\n1 2\n0\n0","output":"1 2"}],"def merge(nums1,m,nums2,n):\n    i,j,k=m-1,n-1,m+n-1\n    while j>=0:\n        if i>=0 and nums1[i]>nums2[j]:\n            nums1[k]=nums1[i]; i-=1\n        else:\n            nums1[k]=nums2[j]; j-=1\n        k-=1")

# === Additional MEDIUM (8) ===
p("Sort Colors","sort-colors","medium",["arrays","sorting","two-pointers"],["Amazon","Meta"],"Sort an array of 0s, 1s, and 2s in-place.",[{"input":"nums=[2,0,2,1,1,0]","output":"[0,0,1,1,2,2]","explanation":""}],"n == nums.length",["Dutch National Flag algorithm"],[{"input":"6\n2 0 2 1 1 0","output":"0 0 1 1 2 2"},{"input":"3\n2 0 1","output":"0 1 2"}],[{"input":"1\n0","output":"0"}],"def sortColors(nums):\n    lo,hi=0,len(nums)-1\n    mid=0\n    while mid<=hi:\n        if nums[mid]==0: nums[lo],nums[mid]=nums[mid],nums[lo]; lo+=1; mid+=1\n        elif nums[mid]==1: mid+=1\n        else: nums[mid],nums[hi]=nums[hi],nums[mid]; hi-=1")

p("Flatten Binary Tree to Linked List","flatten-binary-tree","medium",["trees","linked-list","recursion"],["Amazon","Google","Meta"],"Flatten a binary tree to a linked list in-place.",[{"input":"root=[1,2,5,3,4,null,6]","output":"[1,null,2,null,3,null,4,null,5,null,6]","explanation":""}],"0 <= nodes <= 20000",["Reverse pre-order traversal"],[{"input":"3\n1 2 5","output":"1 null 2 null 5"},{"input":"1\n1","output":"1"}],[{"input":"0\nnull","output":""}],"def flatten(root):\n    if not root: return\n    flatten(root.right)\n    flatten(root.left)\n    root.right=flatten.tail\n    root.left=None\n    flatten.tail=root\nflatten.tail=None")

p("Binary Tree Right Side View","binary-tree-right-side","medium",["trees","bfs","dfs"],["Amazon","Google","Meta"],"Return values of nodes visible from the right side.",[{"input":"root=[1,2,3,null,5,null,4]","output":"[1,3,4]","explanation":""}],"1 <= nodes <= 100",["BFS level order, take last of each level"],[{"input":"4\n1 2 3 5","output":"1 3"},{"input":"1\n1","output":"1"}],[{"input":"0\nnull","output":""}],"from collections import deque\ndef rightSideView(root):\n    if not root: return []\n    result=[]\n    queue=deque([root])\n    while queue:\n        level=[]\n        for _ in range(len(queue)):\n            node=queue.popleft()\n            level.append(node.val)\n            if node.left: queue.append(node.left)\n            if node.right: queue.append(node.right)\n        result.append(level[-1])\n    return result")

p("Kth Smallest Element in a BST","kth-smallest-bst","medium",["trees","binary-search","dfs"],["Amazon","Google","Meta"],"Find the kth smallest element in a BST.",[{"input":"root=[3,1,4,null,2], k=1","output":"1","explanation":""}],"1 <= k <= nodes <= 10^4",["In-order traversal"],[{"input":"4\n3 1 4 2\n1","output":"1"},{"input":"3\n5 3 6\n2","output":"3"}],[{"input":"1\n1\n1","output":"1"}],"def kthSmallest(root, k):\n    stack=[]\n    while root or stack:\n        while root:\n            stack.append(root)\n            root=root.left\n        root=stack.pop()\n        k-=1\n        if k==0: return root.val\n        root=root.right")

p("Partition Equal Subset Sum","partition-equal-subset","medium",["dynamic-programming","arrays"],["Amazon","Google"],"Check if array can be partitioned into two subsets with equal sum.",[{"input":"nums=[1,5,11,5]","output":"true","explanation":""}],"1 <= nums.length <= 200",["Subset sum DP"],[{"input":"4\n1 5 11 5","output":"true"},{"input":"3\n1 2 3","output":"false"}],[{"input":"1\n1","output":"false"}],"def canPartition(nums):\n    total=sum(nums)\n    if total%2: return False\n    target=total//2\n    dp={0}\n    for n in nums:\n        new=set()\n        for s in dp:\n            if s+n==target: return True\n            new.add(s); new.add(s+n)\n        dp=new\n    return target in dp")

p("Construct Binary Tree from Preorder and Inorder","construct-binary-tree","medium",["trees","recursion","arrays"],["Amazon","Google","Meta"],"Build a binary tree from preorder and inorder traversals.",[{"input":"preorder=[3,9,20,15,7], inorder=[9,3,15,20,7]","output":"[3,9,20,null,null,15,7]","explanation":""}],"1 <= nodes <= 3000",["Recursion with hash map for inorder indices"],[{"input":"4\n3 9 20 15\n3 9 15 20","output":"tree"},{"input":"1\n1\n1","output":"1"}],[{"input":"2\n1 2\n2 1","output":"1 null 2"}],"def buildTree(preorder, inorder):\n    if not preorder: return None\n    root=TreeNode(preorder[0])\n    mid=inorder.index(preorder[0])\n    root.left=buildTree(preorder[1:mid+1],inorder[:mid])\n    root.right=buildTree(preorder[mid+1:],inorder[mid+1:])\n    return root")

p("Find Peak Element","find-peak-element","medium",["arrays","binary-search"],["Amazon","Google"],"Find a peak element in the array.",[{"input":"nums=[1,2,3,1]","output":"2","explanation":""}],"1 <= nums.length <= 1000",["Binary search"],[{"input":"4\n1 2 3 1","output":"2"},{"input":"3\n1 2 1","output":"1"}],[{"input":"1\n1","output":"0"}],"def findPeakElement(nums):\n    lo,hi=0,len(nums)-1\n    while lo<hi:\n        mid=(lo+hi)//2\n        if nums[mid]<nums[mid+1]: lo=mid+1\n        else: hi=mid\n    return lo")

p("Evaluate Reverse Polish Notation","evaluate-rpn","medium",["stack","arrays"],["Amazon","Google","Meta"],"Evaluate the value of an arithmetic expression in Reverse Polish Notation.",[{"input":"tokens=[2,1,+,3,*]","output":"9","explanation":"(2+1)*3=9"}],"1 <= tokens.length <= 10^4",["Use a stack"],[{"input":"5\n2 1 + 3 *","output":"9"},{"input":"5\n4 13 5 / +","output":"6"}],[{"input":"3\n10 6 9 / + *","output":"6"}],"def evalRPN(tokens):\n    stack=[]\n    for t in tokens:\n        if t in '+-*/':\n            b,a=stack.pop(),stack.pop()\n            if t=='+': stack.append(a+b)\n            elif t=='-': stack.append(a-b)\n            elif t=='*': stack.append(a*b)\n            else: stack.append(int(a/b))\n        else: stack.append(int(t))\n    return stack[0]")

# === Additional HARD (5) ===
p("Alien Dictionary","alien-dictionary","hard",["graphs","topological-sort","strings"],["Amazon","Google","Meta"],"Given a sorted dictionary of an alien language, find the order of characters.",[{"input":"words=[wrt,wrf,er,ett,rftt]","output":"wertf","explanation":""}],"1 <= words.length <= 100",["Build graph and topological sort"],[{"input":"5\nwrt wrf er ett rftt","output":"wertf"},{"input":"2\nba bc","output":"abc"}],[{"input":"1\na","output":"a"}],"from collections import defaultdict,deque\ndef alienOrder(words):\n    adj={c:set() for w in words for c in w}\n    for i in range(len(words)-1):\n        w1,w2=words[i],words[i+1]\n        for c1,c2 in zip(w1,w2):\n            if c1!=c2: adj[c1].add(c2); break\n        else:\n            if len(w1)>len(w2): return ''\n    indeg={c:0 for c in adj}\n    for c in adj:\n        for n in adj[c]: indeg[n]+=1\n    queue=deque([c for c in indeg if indeg[c]==0])\n    order=[]\n    while queue:\n        c=queue.popleft()\n        order.append(c)\n        for n in adj[c]:\n            indeg[n]-=1\n            if indeg[n]==0: queue.append(n)\n    return ''.join(order) if len(order)==len(adj) else ''")

p("Longest Increasing Path in a Matrix","longest-increasing-path-matrix","hard",["dynamic-programming","dfs","graphs"],["Amazon","Google","Meta"],"Find the length of the longest increasing path in a matrix.",[{"input":"matrix=[[9,9,4],[6,6,8],[2,1,1]]","output":"4","explanation":""}],"m,n <= 200",["DFS with memoization"],[{"input":"3 3\n9 9 4\n6 6 8\n2 1 1","output":"4"},{"input":"1 1\n1","output":"1"}],[{"input":"1 1\n1","output":"1"}],"def longestIncreasingPath(matrix):\n    if not matrix: return 0\n    R,C=len(matrix),len(matrix[0])\n    dp={}\n    def dfs(r,c):\n        if (r,c) in dp: return dp[(r,c)]\n        ans=1\n        for dr,dc in [(0,1),(0,-1),(1,0),(-1,0)]:\n            nr,nc=r+dr,c+dc\n            if 0<=nr<R and 0<=nc<C and matrix[nr][nc]>matrix[r][c]:\n                ans=max(ans,1+dfs(nr,nc))\n        dp[(r,c)]=ans\n        return ans\n    return max(dfs(r,c) for r in range(R) for c in range(C))",2000)

p("Palindrome Pairs","palindrome-pairs","hard",["hash-table","strings","trie"],["Amazon","Google","Meta"],"Find all pairs of indices (i,j) such that words[i]+words[j] is a palindrome.",[{"input":"words=[abcd,dcba,abc,ba]","output":"[[0,1],[1,0],[2,3],[3,2]]","explanation":""}],"1 <= words.length <= 5000",["Use hash map with reversed words"],[{"input":"4\nabcd dcba abc ba","output":"pairs"},{"input":"2\na abc","output":"0 1"}],[{"input":"1\na","output":""}],"def palindromePairs(words):\n    d={w:i for i,w in enumerate(words)}\n    result=[]\n    for i,w in enumerate(words):\n        for j in range(len(w)+1):\n            pre=w[:j]\n            suf=w[j:]\n            if pre==pre[::-1]:\n                rev=suf[::-1]\n                if rev in d and d[rev]!=i: result.append([i,d[rev]])\n            if j>0 and suf==suf[::-1]:\n                rev=pre[::-1]\n                if rev in d and d[rev]!=i: result.append([d[rev],i])\n    return result")

p("Cherry Pickup","cherry-pickup","hard",["dynamic-programming","arrays"],["Amazon","Google"],"Collect maximum cherries on an NxN grid with two robots starting from (0,0) and going to (N-1,N-1) and back.",[{"input":"grid=[[0,1,-1],[1,0,-1],[1,1,1]]","output":"5","explanation":""}],"1 <= grid.length <= 50",["DP with two paths"],[{"input":"3 3\n0 1 -1\n1 0 -1\n1 1 1","output":"5"},{"input":"1 1\n1","output":"1"}],[{"input":"1 1\n1","output":"1"}],"def cherryPickup(grid):\n    N=len(grid)\n    dp={}\n    def dfs(r1,c1,r2):\n        c2=r1+c1-r2\n        if r1>=N or c1>=N or r2>=N or c2>=N or grid[r1][c1]==-1 or grid[r2][c2]==-1:\n            return float('-inf')\n        if r1==N-1 and c1==N-1: return grid[r1][c1]\n        if (r1,c1,r2) in dp: return dp[(r1,c1,r2)]\n        cherries=grid[r1][c1]\n        if r1!=r2 or c1!=c2: cherries+=grid[r2][c2]\n        best=max(dfs(r1+1,c1,r2+1),dfs(r1+1,c1,r2),dfs(r1,c1+1,r2+1),dfs(r1,c1+1,r2))\n        dp[(r1,c1,r2)]=cherries+best\n        return dp[(r1,c1,r2)]\n    return max(0,dfs(0,0,0))",2000)

p("Best Time to Buy and Sell Stock IV","buy-sell-stock-iv","hard",["dynamic-programming","arrays"],["Amazon","Google","Meta"],"Find the maximum profit from at most k transactions.",[{"input":"k=2, prices=[2,4,1]","output":"2","explanation":""}],"0 <= k <= 100",["DP with transaction count"],[{"input":"3\n2 4 1\n2","output":"2"},{"input":"2\n3 2 6 5 0 3\n2","output":"7"}],[{"input":"2\n1 2\n1","output":"1"}],"def maxProfit(k, prices):\n    if not prices: return 0\n    n=len(prices)\n    if k>=n//2:\n        return sum(max(0,prices[i]-prices[i-1]) for i in range(1,n))\n    dp=[[0]*n for _ in range(k+1)]\n    for t in range(1,k+1):\n        maxDiff=-prices[0]\n        for i in range(1,n):\n            dp[t][i]=max(dp[t][i-1],prices[i]+maxDiff)\n            maxDiff=max(maxDiff,dp[t-1][i]-prices[i])\n    return dp[k][n-1]",2000)

# Write to file
import json
with open(r'C:\Users\keerthana\OneDrive\Desktop\main project deepak\placex\backend\app\coding_seed.py', 'w', encoding='utf-8') as f:
    f.write('CODING_PROBLEMS = [\n')
    for i, prob in enumerate(CODING_PROBLEMS):
        line = '    ' + json.dumps(prob, ensure_ascii=False)
        f.write(line + (',\n' if i < len(CODING_PROBLEMS)-1 else '\n'))
    f.write(']\n')

print(f"Written {len(CODING_PROBLEMS)} coding problems to coding_seed.py")
