import asyncio
from app.database import connect_db, disconnect_db
import app.database as db_mod
from app.models import Base, GDTopic, CompanyQuestion, LearningTopic, CodingProblem, AptitudeQuestion
from sqlalchemy import select, func


GD_TOPICS = [
    {"title": "AI and Future Jobs", "category": "technology", "description": "Will AI replace human jobs or create new opportunities?",
     "points_for": ["AI creates new job categories", "Increases productivity", "Handles dangerous tasks", "Frees humans for creative work"],
     "points_against": ["Job displacement in routine tasks", "Widens skill gap", "Bias in AI decisions", "High cost of transition"],
     "key_arguments": ["Reskilling programs are essential", "AI augments rather than replaces", "New roles emerge with AI adoption"],
     "opening_statement": "Artificial intelligence is transforming the workplace at an unprecedented pace. While concerns about job displacement are valid, history shows that technological revolutions ultimately create more jobs than they destroy.",
     "conclusion": "The key is proactive reskilling and education reform to prepare the workforce for AI-augmented roles.", "difficulty": "medium"},
    {"title": "Work From Home vs Office Work", "category": "lifestyle", "description": "Which model is more productive and sustainable?",
     "points_for": ["Better work-life balance", "Reduced commute time", "Cost savings", "Increased flexibility"],
     "points_against": ["Isolation and loneliness", "Blurred work-life boundaries", "Reduced collaboration", "Home distractions"],
     "key_arguments": ["Hybrid models offer the best of both worlds", "Productivity depends on role and individual", "Company culture matters"],
     "opening_statement": "The pandemic fundamentally changed how we work. Now the debate is whether to return to offices or embrace remote work permanently.",
     "conclusion": "A hybrid approach that gives employees flexibility while maintaining collaboration opportunities is the most sustainable path forward.", "difficulty": "easy"},
    {"title": "Social Media: Boon or Bane", "category": "society", "description": "Does social media do more harm than good?",
     "points_for": ["Connects people globally", "Platform for expression", "Business opportunities", "Awareness and education"],
     "points_against": ["Mental health impacts", "Misinformation spread", "Privacy concerns", "Addiction and screen time"],
     "key_arguments": ["Digital literacy is key", "Platform regulation needed", "Responsible usage matters"],
     "opening_statement": "Social media has connected billions of people worldwide, but concerns about its impact on mental health and society are growing.",
     "conclusion": "Social media is a tool - its impact depends on how we use it. Regulation and digital literacy are essential.", "difficulty": "easy"},
    {"title": "Ethics of Artificial Intelligence", "category": "technology", "description": "Should there be strict regulations on AI development?",
     "points_for": ["Prevents misuse", "Protects privacy", "Ensures fairness", "Builds public trust"],
     "points_against": ["Slows innovation", "Hard to enforce globally", "Stifles competition", "Definition of ethics varies"],
     "key_arguments": ["Balanced regulation is needed", "International cooperation required", "Transparency in AI systems"],
     "opening_statement": "As AI systems become more powerful, the question of ethical boundaries becomes increasingly urgent.",
     "conclusion": "A collaborative approach between governments, tech companies, and society is needed to establish ethical AI guidelines.", "difficulty": "hard"},
    {"title": "Climate Change and Young Generation", "category": "environment", "description": "Is the younger generation doing enough to combat climate change?",
     "points_for": ["Youth activism raising awareness", "Adoption of sustainable practices", "Innovation in clean tech", "Voting for climate policies"],
     "points_against": ["Consumer habits contradict values", "Social media activism vs real action", "Limited political power", "Carbon footprint of tech"],
     "key_arguments": ["Systemic change requires policy action", "Individual and collective responsibility", "Technology alone cannot solve climate change"],
     "opening_statement": "Young people today are the most climate-conscious generation, but questions remain about whether awareness translates to action.",
     "conclusion": "While youth awareness is high, translating that into systemic change requires political engagement and corporate accountability.", "difficulty": "medium"},
    {"title": "Startup Ecosystem in India", "category": "business", "description": "Is India's startup ecosystem sustainable?",
     "points_for": ["Innovation and job creation", "Growing investor confidence", "Government support", "Large domestic market"],
     "points_against": ["High failure rates", "Unsustainable valuations", "Regulatory challenges", "Copycat vs innovation"],
     "key_arguments": ["Focus on unit economics", "Sustainable growth over unicorn chase", "Government policy impact"],
     "opening_statement": "India has emerged as the third-largest startup ecosystem globally, but questions about sustainability persist.",
     "conclusion": "Sustainable startups focusing on real problems and unit economics will drive India's growth story.", "difficulty": "medium"},
    {"title": "Online Education vs Traditional Classroom", "category": "education", "description": "Can online education replace traditional learning?",
     "points_for": ["Accessibility", "Flexibility", "Cost-effective", "Self-paced learning"],
     "points_against": ["Lack of social interaction", "Screen fatigue", "Quality concerns", "Digital divide"],
     "key_arguments": ["Blended learning is the future", "Infrastructure gaps need addressing", "Teacher training essential"],
     "opening_statement": "The shift to online education during the pandemic revealed both its potential and limitations.",
     "conclusion": "A blended approach combining online flexibility with classroom interaction offers the best learning outcomes.", "difficulty": "easy"},
    {"title": "Digital India: Progress and Challenges", "category": "technology", "description": "Has India's digital transformation been inclusive?",
     "points_for": ["UPI revolution", "Digital governance", "Financial inclusion", "Rural connectivity improving"],
     "points_against": ["Digital divide persists", "Cybersecurity concerns", "Language barriers", "Rural internet quality"],
     "key_arguments": ["Infrastructure investment needed", "Digital literacy programs essential", "Language localization key"],
     "opening_statement": "India's digital transformation has been remarkable, but ensuring inclusive access remains a challenge.",
     "conclusion": "Bridging the digital divide through infrastructure and literacy programs is essential for truly inclusive digital growth.", "difficulty": "medium"},
    {"title": "Mental Health in Corporate World", "category": "society", "description": "Are companies doing enough for employee mental health?",
     "points_for": ["Growing awareness", "Employee assistance programs", "Flexible work options", "Reduced stigma"],
     "points_against": ["Toxic work cultures persist", "Burnout normalized", "Insufficient support", "Performance pressure"],
     "key_arguments": ["Mental health is a business issue", "Leadership tone matters", "Systemic change needed"],
     "opening_statement": "Workplace stress and burnout have become epidemic, affecting productivity and employee well-being.",
     "conclusion": "Companies must treat mental health as a priority, not a perk, through systemic culture change.", "difficulty": "medium"},
    {"title": "Space Exploration: Worth the Investment?", "category": "science", "description": "Should developing countries invest in space programs?",
     "points_for": ["Technological spinoffs", "National pride", "Resource discovery", "Long-term survival"],
     "points_against": ["Immediate needs unmet", "Opportunity cost", "International cooperation needed", "Environmental impact"],
     "key_arguments": ["Balanced investment approach", "International collaboration", "Technology transfer benefits"],
     "opening_statement": "As countries invest billions in space programs, questions about prioritization arise.",
     "conclusion": "Space investment is justified when balanced with addressing immediate societal needs.", "difficulty": "hard"},
    {"title": "Impact of OTT Platforms on Cinema", "category": "entertainment", "description": "Are OTT platforms killing traditional cinema?",
     "points_for": ["Content democratization", "Global reach", "Creative freedom", "Convenience"],
     "points_against": ["Theatrical experience declining", "Revenue model challenges", "Content overload", "Cinema jobs affected"],
     "key_arguments": ["Coexistence is possible", "Different experiences serve different needs", "Content quality matters"],
     "opening_statement": "The rise of OTT platforms has fundamentally changed how we consume entertainment.",
     "conclusion": "OTT and cinema can coexist, each offering unique experiences to audiences.", "difficulty": "easy"},
    {"title": "Government Surveillance vs Privacy", "category": "politics", "description": "Is mass surveillance justified for national security?",
     "points_for": ["Crime prevention", "National security", "Terrorism prevention", "Public safety"],
     "points_against": ["Privacy violation", "Chilling effect on freedom", "Potential for abuse", "Mass data collection risks"],
     "key_arguments": ["Oversight mechanisms essential", "Proportionality principle", "Transparency needed"],
     "opening_statement": "In an age of digital communication, governments face the challenge of balancing security with privacy.",
     "conclusion": "Robust oversight and transparency mechanisms are essential to prevent surveillance overreach.", "difficulty": "hard"},
    {"title": "Plastic Ban: Solution or Inconvenience?", "category": "environment", "description": "Are plastic bans effective in reducing pollution?",
     "points_for": ["Reduces pollution", "Encourages alternatives", "Health benefits", "Environmental protection"],
     "points_against": ["Inconvenience to businesses", "Alternative costs higher", "Enforcement challenges", "Incomplete solution"],
     "key_arguments": ["Comprehensive approach needed", "Industry transition support", "Consumer behavior change"],
     "opening_statement": "Plastic bans are being implemented worldwide, but their effectiveness is debated.",
     "conclusion": "Plastic bans work best when accompanied by affordable alternatives and proper enforcement.", "difficulty": "easy"},
    {"title": "Reservation System in India", "category": "politics", "description": "Should reservation be based on economic status rather than caste?",
     "points_for": ["Addresses current inequality", "Merit-based opportunity", "Economic upliftment", "Modern approach"],
     "points_against": ["Historical injustice remains", "Caste discrimination persists", "Implementation challenges", "Political implications"],
     "key_arguments": ["Dual approach needed", "Data-driven policy", "Focus on quality education"],
     "opening_statement": "India's reservation system is one of the world's largest affirmative action programs, but debates about its form continue.",
     "conclusion": "A balanced approach considering both caste and economic factors may be the most equitable path forward.", "difficulty": "hard"},
    {"title": "Autonomous Vehicles: Ready for the Road?", "category": "technology", "description": "Should self-driving cars be allowed on public roads now?",
     "points_for": ["Reduced accidents", "Accessibility for disabled", "Traffic optimization", "Technology readiness"],
     "points_against": ["Safety concerns", "Job displacement", "Ethical dilemmas", "Infrastructure needs"],
     "key_arguments": ["Gradual rollout with oversight", "Regulatory framework essential", "Public trust building"],
     "opening_statement": "Self-driving technology is advancing rapidly, but the question of public road readiness remains.",
     "conclusion": "Autonomous vehicles need robust regulation and proven safety records before widespread adoption.", "difficulty": "medium"},
]

CODING_PROBLEMS = [
    {"title": "Two Sum", "slug": "two-sum", "difficulty": "easy", "topics": ["arrays", "hash-table"], "companies": ["Amazon", "Google", "Meta"], "description": "Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.", "examples": [{"input": "nums = [2,7,11,15], target = 9", "output": "[0,1]", "explanation": "Because nums[0] + nums[1] == 9, we return [0, 1]"}], "constraints": "2 <= nums.length <= 10^4\n-10^9 <= nums[i] <= 10^9\n-10^9 <= target <= 10^9\nOnly one valid answer exists.", "hints": ["A really brute force way would be to search for all possible pairs of numbers but that would be too slow."], "test_cases": [{"input": "2\n4\n2 7 11 15\n9", "output": "0 1"}, {"input": "3\n3\n3 2 4\n6", "output": "1 2"}], "hidden_test_cases": [{"input": "2\n2\n3 3\n6", "output": "0 1"}], "solution": {"python": "class Solution:\n    def twoSum(self, nums, target):\n        seen = {}\n        for i, n in enumerate(nums):\n            comp = target - n\n            if comp in seen:\n                return [seen[comp], i]\n            seen[n] = i"}, "time_limit": 1000, "memory_limit": 256},
    {"title": "Reverse String", "slug": "reverse-string", "difficulty": "easy", "topics": ["strings", "two-pointers"], "companies": ["Microsoft", "Apple"], "description": "Write a function that reverses a string. The input string is given as an array of characters `s`.\n\nYou must do this by modifying the input array in-place with O(1) extra memory.", "examples": [{"input": 's = ["h","e","l","l","o"]', "output": '["o","l","l","e","h"]', "explanation": ""}], "constraints": "1 <= s.length <= 10^5\ns[i] is a printable ascii character.", "hints": ["The entire logic for reversing a string is based on using the two-pointer technique."], "test_cases": [{"input": "5\nhello", "output": "olleh"}, {"input": "1\nA", "output": "A"}], "hidden_test_cases": [{"input": "7\nA man a plan a canal Panama", "output": "amonaP lacnaC a nalp a nam A"}], "solution": {"python": "class Solution:\n    def reverseString(self, s):\n        s[:] = s[::-1]"}, "time_limit": 1000, "memory_limit": 256},
    {"title": "Valid Parentheses", "slug": "valid-parentheses", "difficulty": "easy", "topics": ["stack", "strings"], "companies": ["Amazon", "Meta", "Bloomberg"], "description": "Given a string `s` containing just the characters `'('`, `')'`, `'{'`, `'}'`, `'['` and `']'`, determine if the input string is valid.\n\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n3. Every close bracket has a corresponding open bracket of the same type.", "examples": [{"input": 's = "()"', "output": "true", "explanation": ""}], "constraints": "1 <= s.length <= 10^4\ns consists of parentheses only '()[]{}'.", "hints": ["Use a stack to keep track of opening brackets."], "test_cases": [{"input": "2\n()", "output": "true"}, {"input": "3\n([])", "output": "true"}], "hidden_test_cases": [{"input": "6\n([{}])", "output": "true"}], "solution": {"python": "class Solution:\n    def isValid(self, s):\n        stack = []\n        map = {')':'(', ']':'[', '}':'{'}\n        for c in s:\n            if c in map:\n                if not stack or stack[-1] != map[c]: return False\n                stack.pop()\n            else:\n                stack.append(c)\n        return not stack"}, "time_limit": 1000, "memory_limit": 256},
    {"title": "Maximum Subarray", "slug": "maximum-subarray", "difficulty": "medium", "topics": ["arrays", "dynamic-programming"], "companies": ["Google", "Amazon", "Apple"], "description": "Given an integer array `nums`, find the subarray with the largest sum, and return its sum.", "examples": [{"input": "nums = [-2,1,-3,4,-1,2,1,-5,4]", "output": "6", "explanation": "The subarray [4,-1,2,1] has the largest sum 6."}], "constraints": "1 <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4", "hints": ["Think of Kadane's algorithm."], "test_cases": [{"input": "9\n-2 1 -3 4 -1 2 1 -5 4", "output": "6"}, {"input": "1\n1", "output": "1"}], "hidden_test_cases": [{"input": "5\n5 4 -1 7 8", "output": "23"}], "solution": {"python": "class Solution:\n    def maxSubArray(self, nums):\n        cur = max_sum = nums[0]\n        for n in nums[1:]:\n            cur = max(n, cur + n)\n            max_sum = max(max_sum, cur)\n        return max_sum"}, "time_limit": 1000, "memory_limit": 256},
    {"title": "Merge Two Sorted Lists", "slug": "merge-two-sorted-lists", "difficulty": "easy", "topics": ["linked-list", "recursion"], "companies": ["Microsoft", "Amazon"], "description": "You are given the heads of two sorted linked lists `list1` and `list2`.\n\nMerge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.\n\nReturn the head of the merged linked list.", "examples": [{"input": "list1 = [1,2,4], list2 = [1,3,4]", "output": "[1,1,2,3,4,4]", "explanation": ""}], "constraints": "Both lists are sorted in non-decreasing order.", "hints": ["Use a dummy node to simplify edge cases."], "test_cases": [{"input": "3\n1 2 4\n3\n1 3 4", "output": "1 1 2 3 4 4"}, {"input": "0\n\n0\n\n", "output": ""}], "hidden_test_cases": [{"input": "1\n2\n1\n1", "output": "1 2"}], "solution": {"python": "class Solution:\n    def mergeTwoLists(self, list1, list2):\n        if not list1: return list2\n        if not list2: return list1\n        if list1.val <= list2.val:\n            list1.next = self.mergeTwoLists(list1.next, list2)\n            return list1\n        list2.next = self.mergeTwoLists(list1, list2.next)\n        return list2"}, "time_limit": 1000, "memory_limit": 256},
    {"title": "Best Time to Buy and Sell Stock", "slug": "best-time-to-buy-and-sell-stock", "difficulty": "easy", "topics": ["arrays", "dynamic-programming"], "companies": ["Amazon", "Meta", "Google"], "description": "You are given an array `prices` where `prices[i]` is the price of a given stock on the ith day.\n\nYou want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.\n\nReturn the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.", "examples": [{"input": "prices = [7,1,5,3,6,4]", "output": "5", "explanation": "Buy on day 2 (price=1) and sell on day 5 (price=6), profit = 6-1 = 5."}], "constraints": "1 <= prices.length <= 10^5\n0 <= prices[i] <= 10^4", "hints": ["Track the minimum price seen so far."], "test_cases": [{"input": "6\n7 1 5 3 6 4", "output": "5"}, {"input": "5\n7 6 4 3 1", "output": "0"}], "hidden_test_cases": [{"input": "4\n2 4 1 7", "output": "5"}], "solution": {"python": "class Solution:\n    def maxProfit(self, prices):\n        min_price = float('inf')\n        max_profit = 0\n        for p in prices:\n            min_price = min(min_price, p)\n            max_profit = max(max_profit, p - min_price)\n        return max_profit"}, "time_limit": 1000, "memory_limit": 256},
    {"title": "Binary Search", "slug": "binary-search", "difficulty": "easy", "topics": ["arrays", "searching"], "companies": ["Microsoft", "Amazon"], "description": "Given an array of integers `nums` which is sorted in ascending order, and an integer `target`, write a function to search `target` in `nums`. If `target` exists, then return its index. Otherwise, return -1.\n\nYou must write an algorithm with O(log n) runtime complexity.", "examples": [{"input": "nums = [-1,0,3,5,9,12], target = 9", "output": "4", "explanation": "9 exists in nums and its index is 4"}], "constraints": "All the integers in nums are unique.\nnums is sorted in ascending order.", "hints": ["Classic binary search template."], "test_cases": [{"input": "6\n-1 0 3 5 9 12\n9", "output": "4"}, {"input": "6\n-1 0 3 5 9 12\n2", "output": "-1"}], "hidden_test_cases": [{"input": "1\n5\n5", "output": "0"}], "solution": {"python": "class Solution:\n    def search(self, nums, target):\n        lo, hi = 0, len(nums) - 1\n        while lo <= hi:\n            mid = (lo + hi) // 2\n            if nums[mid] == target: return mid\n            elif nums[mid] < target: lo = mid + 1\n            else: hi = mid - 1\n        return -1"}, "time_limit": 1000, "memory_limit": 256},
    {"title": "Climbing Stairs", "slug": "climbing-stairs", "difficulty": "easy", "topics": ["dynamic-programming", "math"], "companies": ["Amazon", "Apple", "Google"], "description": "You are climbing a staircase. It takes `n` steps to reach the top.\n\nEach time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?", "examples": [{"input": "n = 2", "output": "2", "explanation": "1. 1 step + 1 step\n2. 2 steps"}], "constraints": "1 <= n <= 45", "hints": ["This is a Fibonacci sequence problem."], "test_cases": [{"input": "2", "output": "2"}, {"input": "3", "output": "3"}], "hidden_test_cases": [{"input": "5", "output": "8"}], "solution": {"python": "class Solution:\n    def climbStairs(self, n):\n        if n <= 2: return n\n        a, b = 1, 2\n        for _ in range(3, n + 1):\n            a, b = b, a + b\n        return b"}, "time_limit": 1000, "memory_limit": 256},
    {"title": "Longest Common Subsequence", "slug": "longest-common-subsequence", "difficulty": "medium", "topics": ["dynamic-programming", "strings"], "companies": ["Amazon", "Google", "Microsoft"], "description": "Given two strings `text1` and `text2`, return the length of their longest common subsequence. If there is no common subsequence, return 0.\n\nA subsequence of a string is a new string generated from the original string with some characters (can be none) deleted without changing the relative order of the remaining characters.", "examples": [{"input": 'text1 = "abcde", text2 = "ace"', "output": "3", "explanation": 'The longest common subsequence is "ace" and its length is 3.'}], "constraints": "1 <= text1.length, text2.length <= 1000\ntext1 and text2 consist of only lowercase English characters.", "hints": ["Use a 2D DP table where dp[i][j] = LCS length of text1[:i] and text2[:j]."], "test_cases": [{"input": "5\nabcde\n3\nace", "output": "3"}, {"input": "7\nabcdefg\n5\nacefg", "output": "4"}], "hidden_test_cases": [{"input": "3\nabc\n3\ndef", "output": "0"}], "solution": {"python": "class Solution:\n    def longestCommonSubsequence(self, text1, text2):\n        m, n = len(text1), len(text2)\n        dp = [[0]*(n+1) for _ in range(m+1)]\n        for i in range(1, m+1):\n            for j in range(1, n+1):\n                if text1[i-1] == text2[j-1]:\n                    dp[i][j] = dp[i-1][j-1] + 1\n                else:\n                    dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n        return dp[m][n]"}, "time_limit": 1000, "memory_limit": 256},
    {"title": "Number of Islands", "slug": "number-of-islands", "difficulty": "medium", "topics": ["graphs", "dfs", "bfs"], "companies": ["Amazon", "Google", "Meta"], "description": "Given an `m x n` 2D binary grid `grid` which represents a map of '1's (land) and '0's (water), return the number of islands.\n\nAn island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.", "examples": [{"input": 'grid = [["1","1","0"],["1","0","0"],["0","0","1"]]', "output": "2", "explanation": ""}], "constraints": "m == grid.length\nn == grid[i].length\n1 <= m, n <= 300\ngrid[i][j] is '0' or '1'.", "hints": ["Use BFS or DFS to explore each island."], "test_cases": [{"input": "3 3\n1 1 0\n1 0 0\n0 0 1", "output": "2"}, {"input": "3 3\n1 1 1\n1 1 1\n1 1 1", "output": "1"}], "hidden_test_cases": [{"input": "2 2\n1 1\n1 1", "output": "1"}], "solution": {"python": "class Solution:\n    def numIslands(self, grid):\n        if not grid: return 0\n        count = 0\n        for i in range(len(grid)):\n            for j in range(len(grid[0])):\n                if grid[i][j] == '1':\n                    self.dfs(grid, i, j)\n                    count += 1\n        return count\n    def dfs(self, grid, i, j):\n        if i<0 or j<0 or i>=len(grid) or j>=len(grid[0]) or grid[i][j]!='1': return\n        grid[i][j] = '0'\n        self.dfs(grid,i+1,j); self.dfs(grid,i-1,j)\n        self.dfs(grid,i,j+1); self.dfs(grid,i,j-1)"}, "time_limit": 2000, "memory_limit": 256},
    {"title": "Coin Change", "slug": "coin-change", "difficulty": "medium", "topics": ["dynamic-programming", "arrays"], "companies": ["Amazon", "Microsoft", "Google"], "description": "You are given an integer array `coins` representing coins of different denominations and an integer `amount` representing a total amount of money.\n\nReturn the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.", "examples": [{"input": "coins = [1,5,10,25], amount = 30", "output": "2", "explanation": "5 + 25 = 30"}], "constraints": "1 <= coins.length <= 12\n1 <= coins[i] <= 2^31 - 1\n0 <= amount <= 10^4", "hints": ["Think of this as a bottom-up DP problem."], "test_cases": [{"input": "4\n1 5 10 25\n30", "output": "2"}, {"input": "3\n1 2 5\n11", "output": "3"}], "hidden_test_cases": [{"input": "1\n2\n3", "output": "-1"}], "solution": {"python": "class Solution:\n    def coinChange(self, coins, amount):\n        dp = [float('inf')] * (amount + 1)\n        dp[0] = 0\n        for i in range(1, amount + 1):\n            for c in coins:\n                if c <= i and dp[i-c] + 1 < dp[i]:\n                    dp[i] = dp[i-c] + 1\n        return dp[amount] if dp[amount] != float('inf') else -1"}, "time_limit": 2000, "memory_limit": 256},
    {"title": "LRU Cache", "slug": "lru-cache", "difficulty": "hard", "topics": ["hash-table", "linked-list", "design"], "companies": ["Amazon", "Google", "Meta", "Microsoft"], "description": "Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.\n\nImplement the `LRUCache` class with `get` and `put` methods, each running in O(1) time complexity.", "examples": [{"input": '["LRUCache","put","get","put","get","get"]\\n[[2],[1,1],[1],[2,2],[1],[2]]', "output": "[null,null,1,null,-1,2]", "explanation": ""}], "constraints": "1 <= capacity <= 3000\n0 <= key <= 10^4\n0 <= value <= 10^5", "hints": ["Use a hash map combined with a doubly linked list."], "test_cases": [{"input": "2\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2", "output": "1\n-1"}], "hidden_test_cases": [{"input": "1\nput 1 1\nput 2 2\nget 1", "output": "-1"}], "solution": {"python": "from collections import OrderedDict\nclass LRUCache:\n    def __init__(self, capacity):\n        self.cache = OrderedDict()\n        self.cap = capacity\n    def get(self, key):\n        if key not in self.cache: return -1\n        self.cache.move_to_end(key)\n        return self.cache[key]\n    def put(self, key, value):\n        if key in self.cache: self.cache.move_to_end(key)\n        self.cache[key] = value\n        if len(self.cache) > self.cap: self.cache.popitem(last=False)"}, "time_limit": 2000, "memory_limit": 256},
    {"title": "Serialize and Deserialize Binary Tree", "slug": "serialize-and-deserialize-binary-tree", "difficulty": "hard", "topics": ["trees", "design", "bfs"], "companies": ["Amazon", "Google", "Meta", "Microsoft"], "description": "Design an algorithm to serialize and deserialize a binary tree. There is no restriction on how your serialization/deserialization algorithm should work.\n\nYou need to ensure a binary tree can be serialized to a string and this string can be deserialized to the original tree structure.", "examples": [{"input": "root = [1,2,3,null,null,4,5]", "output": "[1,2,3,null,null,4,5]", "explanation": ""}], "constraints": "The number of nodes in the tree is in the range [0, 10^4].\n-1000 <= Node.val <= 1000", "hints": ["Pre-order traversal works well for serialization."], "test_cases": [{"input": "5\n1 2 3 null null 4 5", "output": "1 2 3 null null 4 5"}, {"input": "1\n1", "output": "1"}], "hidden_test_cases": [{"input": "0\nnull", "output": "null"}], "solution": {"python": "class Codec:\n    def serialize(self, root):\n        if not root: return 'null'\n        return f'{root.val},{self.serialize(root.left)},{self.serialize(root.right)}'\n    def deserialize(self, data):\n        def helper(it):\n            val = next(it)\n            if val == 'null': return None\n            node = TreeNode(int(val))\n            node.left = helper(it)\n            node.right = helper(it)\n            return node\n        return helper(iter(data.split(',')))"}, "time_limit": 2000, "memory_limit": 256},
    {"title": "Median of Two Sorted Arrays", "slug": "median-of-two-sorted-arrays", "difficulty": "hard", "topics": ["arrays", "binary-search", "divide-and-conquer"], "companies": ["Google", "Amazon", "Microsoft", "Apple"], "description": "Given two sorted arrays `nums1` and `nums2` of size `m` and `n` respectively, return the median of the two sorted arrays.\n\nThe overall run time complexity should be O(log (m+n)).", "examples": [{"input": "nums1 = [1,3], nums2 = [2]", "output": "2.0", "explanation": "merged array = [1,2,3] and median is 2."}], "constraints": "nums1.length == m\nnums2.length == n\n0 <= m <= 1000\n0 <= n <= 1000", "hints": ["Think about binary search on the smaller array."], "test_cases": [{"input": "2\n1 3\n1\n2", "output": "2.0"}, {"input": "2\n1 2\n2\n3 4", "output": "2.5"}], "hidden_test_cases": [{"input": "1\n2\n1\n1", "output": "1.0"}], "solution": {"python": "class Solution:\n    def findMedianSortedArrays(self, nums1, nums2):\n        if len(nums1) > len(nums2): nums1, nums2 = nums2, nums1\n        m, n = len(nums1), len(nums2)\n        lo, hi = 0, m\n        while lo <= hi:\n            i = (lo + hi) // 2\n            j = (m + n + 1) // 2 - i\n            left = nums1[i-1] if i > 0 else float('-inf')\n            right = nums1[i] if i < m else float('inf')\n            if left <= nums2[j] and nums2[j-1] <= right:\n                if (m+n)%2==1: return max(nums1[i-1],nums2[j-1])\n                return (max(nums1[i-1],nums2[j-1])+min(nums1[i],nums2[j]))/2\n            elif left > nums2[j]: hi = i-1\n            else: lo = i+1"}, "time_limit": 2000, "memory_limit": 256},
    {"title": "Trapping Rain Water", "slug": "trapping-rain-water", "difficulty": "hard", "topics": ["arrays", "two-pointers", "stack"], "companies": ["Amazon", "Google", "Goldman Sachs"], "description": "Given `n` non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.", "examples": [{"input": "height = [0,1,0,2,1,0,1,3,2,1,2,1]", "output": "6", "explanation": "6 units of rain water are trapped."}], "constraints": "n == height.length\n1 <= n <= 2 * 10^4\n0 <= height[i] <= 10^5", "hints": ["Use two pointers to track left and right max."], "test_cases": [{"input": "12\n0 1 0 2 1 0 1 3 2 1 2 1", "output": "6"}, {"input": "6\n4 2 0 3 2 5", "output": "9"}], "hidden_test_cases": [{"input": "3\n1 0 1", "output": "1"}], "solution": {"python": "class Solution:\n    def trap(self, height):\n        if not height: return 0\n        l, r = 0, len(height)-1\n        l_max = r_max = ans = 0\n        while l < r:\n            l_max = max(l_max, height[l])\n            r_max = max(r_max, height[r])\n            if l_max < r_max:\n                ans += l_max - height[l]\n                l += 1\n            else:\n                ans += r_max - height[r]\n                r -= 1\n        return ans"}, "time_limit": 2000, "memory_limit": 256},
    {"title": "Word Break", "slug": "word-break", "difficulty": "medium", "topics": ["dynamic-programming", "hash-table", "strings"], "companies": ["Meta", "Amazon", "Apple"], "description": "Given a string `s` and a dictionary of strings `wordDict`, return `true` if `s` can be segmented into a space-separated sequence of one or more dictionary words.", "examples": [{"input": 's = "leetcode", wordDict = ["leet","code"]', "output": "true", "explanation": '"leetcode" can be segmented as "leet code".'}], "constraints": "1 <= s.length <= 300\n1 <= wordDict.length <= 1000\n1 <= wordDict[i].length <= 20\ns and wordDict[i] consist of only lowercase English letters.", "hints": ["Use DP where dp[i] = True if s[:i] can be segmented."], "test_cases": [{"input": "8\nleetcode\n2\nleet code", "output": "true"}, {"input": "7\ncatsandog\n5\ncats dog sand and cat", "output": "false"}], "hidden_test_cases": [{"input": "3\nabc\n3\na b c", "output": "true"}], "solution": {"python": "class Solution:\n    def wordBreak(self, s, wordDict):\n        words = set(wordDict)\n        dp = [False]*(len(s)+1)\n        dp[0] = True\n        for i in range(1,len(s)+1):\n            for j in range(i):\n                if dp[j] and s[j:i] in words:\n                    dp[i] = True\n                    break\n        return dp[-1]"}, "time_limit": 2000, "memory_limit": 256},
    {"title": "Implement Trie", "slug": "implement-trie", "difficulty": "medium", "topics": ["trees", "design", "hash-table"], "companies": ["Amazon", "Google", "Microsoft"], "description": "Implement a trie with `insert`, `search`, and `startsWith` methods.", "examples": [{"input": '["Trie","insert","search","search","startsWith","insert","search"]\\n[[],["apple"],["apple"],["app"],["app"],["app"],["app"]]', "output": "[null,null,true,false,true,null,true]", "explanation": ""}], "constraints": "1 <= word.length, prefix.length <= 2000\nAt most 3 * 10^4 calls will be made.", "hints": ["Each node stores a map of children and an end-of-word flag."], "test_cases": [{"input": "insert apple\nsearch apple\nsearch app\nstartsWith app", "output": "true\nfalse\ntrue"}, {"input": "insert cat\nsearch cat\nsearch dog", "output": "true\nfalse"}], "hidden_test_cases": [{"input": "insert a\nstartsWith a\nsearch a", "output": "true\ntrue"}], "solution": {"python": "class TrieNode:\n    def __init__(self):\n        self.children = {}\n        self.is_end = False\nclass Trie:\n    def __init__(self):\n        self.root = TrieNode()\n    def insert(self, word):\n        node = self.root\n        for c in word:\n            if c not in node.children: node.children[c] = TrieNode()\n            node = node.children[c]\n        node.is_end = True\n    def search(self, word):\n        node = self.root\n        for c in word:\n            if c not in node.children: return False\n            node = node.children[c]\n        return node.is_end\n    def startsWith(self, prefix):\n        node = self.root\n        for c in prefix:\n            if c not in node.children: return False\n            node = node.children[c]\n        return True"}, "time_limit": 2000, "memory_limit": 256},
    {"title": "Find All Anagrams in a String", "slug": "find-all-anagrams-in-a-string", "difficulty": "medium", "topics": ["hash-table", "sliding-window", "strings"], "companies": ["Amazon", "Meta"], "description": "Given two strings `s` and `p`, return an array of all the start indices of `p`'s anagrams in `s`. You may return the answer in any order.", "examples": [{"input": 's = "cbaebabacd", p = "abc"', "output": "[0,6]", "explanation": ""}], "constraints": "1 <= s.length, p.length <= 3 * 10^4\ns and p consist of lowercase English letters.", "hints": ["Use a sliding window with character frequency counts."], "test_cases": [{"input": "10\ncbaebabacd\n3\nabc", "output": "0 6"}, {"input": "7\nabab\n3\nab", "output": "0 1 2"}], "hidden_test_cases": [{"input": "6\naabaab\n3\naba", "output": "1"}], "solution": {"python": "from collections import Counter\nclass Solution:\n    def findAnagrams(self, s, p):\n        pc, sc = Counter(p), Counter()\n        res = []\n        for i, c in enumerate(s):\n            sc[c] += 1\n            if i >= len(p): sc[s[i-len(p)]] -= 1\n            if sc == pc: res.append(i-len(p)+1)\n        return res"}, "time_limit": 2000, "memory_limit": 256},
    {"title": "Task Scheduler", "slug": "task-scheduler", "difficulty": "hard", "topics": ["hash-table", "greedy", "sorting", "heap"], "companies": ["Meta", "Amazon", "Microsoft"], "description": "Given a characters array `tasks`, representing the tasks a CPU needs to do, where each letter represents a different task. The CPU can do only one task at a time.\n\nEach task can be done in one interval. Each interval can be delayed by at most `n` units of time due to cooldown period.\n\nReturn the least number of intervals the CPU will take to finish all the given tasks.", "examples": [{"input": 'tasks = ["A","A","A","B","B","B"], n = 2', "output": "8", "explanation": "A->B->idle->A->B->idle->A->B"}], "constraints": "1 <= tasks.length <= 10^4\ntasks[i] is upper-case English letter.\n0 <= n <= 100", "hints": ["The answer depends on the frequency of the most frequent task."], "test_cases": [{"input": "6\nA A A B B B\n2", "output": "8"}, {"input": "4\nA A A A\n2", "output": "10"}], "hidden_test_cases": [{"input": "3\nA B A\n2", "output": "4"}], "solution": {"python": "from collections import Counter\nclass Solution:\n    def leastInterval(self, tasks, n):\n        freq = Counter(tasks)\n        max_freq = max(freq.values())\n        max_count = sum(1 for v in freq.values() if v == max_freq)\n        return max(len(tasks), (max_freq-1)*(n+1)+max_count)"}, "time_limit": 2000, "memory_limit": 256},
]

APTITUDE_QUESTIONS = [
    {"topic": "Quantitative", "subtopic": "Percentage", "difficulty": "easy", "question": "What is 20% of 150?", "options": ["25", "30", "35", "40"], "correct_index": 1, "explanation": "20% of 150 = 0.20 * 150 = 30"},
    {"topic": "Quantitative", "subtopic": "Percentage", "difficulty": "easy", "question": "A number is increased by 20% and then decreased by 20%. What is the net change?", "options": ["No change", "4% increase", "4% decrease", "2% decrease"], "correct_index": 2, "explanation": "Net change = -20% + 20% - (20*20)/100 = -4%"},
    {"topic": "Quantitative", "subtopic": "Profit & Loss", "difficulty": "medium", "question": "A shopkeeper buys an article for Rs. 500 and sells it for Rs. 650. What is the profit percentage?", "options": ["25%", "30%", "35%", "15%"], "correct_index": 1, "explanation": "Profit = 650-500 = 150. Profit% = (150/500)*100 = 30%"},
    {"topic": "Quantitative", "subtopic": "Profit & Loss", "difficulty": "medium", "question": "If the cost price of 20 articles is equal to the selling price of 15 articles, find the profit percent.", "options": ["25%", "33.33%", "20%", "15%"], "correct_index": 1, "explanation": "Profit% = (20-15)/15 * 100 = 33.33%"},
    {"topic": "Quantitative", "subtopic": "Simple Interest", "difficulty": "easy", "question": "What is the simple interest on Rs. 5000 at 8% per annum for 3 years?", "options": ["Rs. 1000", "Rs. 1200", "Rs. 1500", "Rs. 800"], "correct_index": 1, "explanation": "SI = P*R*T/100 = 5000*8*3/100 = 1200"},
    {"topic": "Quantitative", "subtopic": "Compound Interest", "difficulty": "medium", "question": "What is the compound interest on Rs. 10000 for 2 years at 10% per annum compounded annually?", "options": ["Rs. 2000", "Rs. 2100", "Rs. 2200", "Rs. 1900"], "correct_index": 1, "explanation": "A = 10000(1.1)^2 = 12100. CI = 12100-10000 = 2100"},
    {"topic": "Quantitative", "subtopic": "Ratio & Proportion", "difficulty": "easy", "question": "If A:B = 2:3 and B:C = 4:5, find A:B:C.", "options": ["8:12:15", "2:3:5", "4:6:5", "8:12:20"], "correct_index": 0, "explanation": "A:B = 2:3 = 8:12, B:C = 4:5 = 12:15. So A:B:C = 8:12:15"},
    {"topic": "Quantitative", "subtopic": "Time & Work", "difficulty": "medium", "question": "A can do a work in 10 days and B can do it in 15 days. In how many days can they together finish the work?", "options": ["5 days", "6 days", "7 days", "8 days"], "correct_index": 1, "explanation": "Combined rate = 1/10 + 1/15 = 5/30 = 1/6. So 6 days."},
    {"topic": "Quantitative", "subtopic": "Time & Distance", "difficulty": "medium", "question": "A car travels 150 km in 3 hours. What is its speed in m/s?", "options": ["50 m/s", "25 m/s", "125/9 m/s", "15 m/s"], "correct_index": 2, "explanation": "Speed = 150/3 = 50 km/h = 50 * 5/18 = 125/9 m/s"},
    {"topic": "Quantitative", "subtopic": "Number Series", "difficulty": "easy", "question": "What comes next: 2, 6, 12, 20, 30, ?", "options": ["40", "42", "36", "44"], "correct_index": 1, "explanation": "Differences: 4, 6, 8, 10, 12. Next = 30+12 = 42"},
    {"topic": "Logical Reasoning", "subtopic": "Coding-Decoding", "difficulty": "easy", "question": "If COMPUTER is coded as RFUVQNPC, how is MEDICINE coded?", "options": ["EOJDJEFM", "FOJDJEFN", "FDJDJEFM", "EOJEIDFM"], "correct_index": 0, "explanation": "Each letter is mapped to its reverse position pattern"},
    {"topic": "Logical Reasoning", "subtopic": "Blood Relations", "difficulty": "medium", "question": "Pointing to a man, a woman said: 'He is the son of my mother's only daughter.' How is the man related to the woman?", "options": ["Son", "Brother", "Nephew", "Husband"], "correct_index": 0, "explanation": "My mother's only daughter = myself. So he is my son."},
    {"topic": "Logical Reasoning", "subtopic": "Direction Sense", "difficulty": "medium", "question": "Rahul walks 10m north, turns right and walks 5m, turns right again and walks 10m. Which direction is he facing?", "options": ["North", "South", "East", "West"], "correct_index": 2, "explanation": "After two right turns from North, he faces East"},
    {"topic": "Logical Reasoning", "subtopic": "Syllogism", "difficulty": "hard", "question": "Statements: All dogs are cats. All cats are birds. Conclusions: I. All dogs are birds. II. All birds are dogs.", "options": ["Only I follows", "Only II follows", "Both follow", "Neither follows"], "correct_index": 0, "explanation": "By syllogism, All dogs are cats + All cats are birds = All dogs are birds"},
    {"topic": "Logical Reasoning", "subtopic": "Seating Arrangement", "difficulty": "hard", "question": "Five people A, B, C, D, E sit in a row. A sits next to B. C sits at one end. D does not sit next to C. Who sits in the middle?", "options": ["A", "B", "C", "D"], "correct_index": 1, "explanation": "Arrangement: C A B D E or E D B A C. B is in the middle."},
    {"topic": "Verbal Ability", "subtopic": "Synonyms", "difficulty": "easy", "question": "Choose the synonym of 'ABANDON':", "options": ["Keep", "Retain", "Desert", "Maintain"], "correct_index": 2, "explanation": "Abandon means to give up or desert"},
    {"topic": "Verbal Ability", "subtopic": "Antonyms", "difficulty": "easy", "question": "Choose the antonym of 'BENEVOLENT':", "options": ["Kind", "Generous", "Malevolent", "Charitable"], "correct_index": 2, "explanation": "Benevolent means kind; Malevolent means harmful"},
    {"topic": "Verbal Ability", "subtopic": "Error Detection", "difficulty": "medium", "question": "Find the error: 'Each of the boys have completed their homework.'", "options": ["Each of", "the boys", "have completed", "their homework"], "correct_index": 2, "explanation": "'Each' is singular, so it should be 'has completed'"},
    {"topic": "Verbal Ability", "subtopic": "Sentence Improvement", "difficulty": "medium", "question": "Improve: 'The news are not correct.'", "options": ["The news is not correct", "The news were not correct", "The news has not correct", "No improvement"], "correct_index": 0, "explanation": "'News' is uncountable and takes singular verb 'is'"},
    {"topic": "Verbal Ability", "subtopic": "Reading Comprehension", "difficulty": "hard", "question": "A passage states: 'The ocean covers 71% of Earth's surface and contains 97% of its water.' What percentage of Earth's surface is NOT covered by ocean?", "options": ["19%", "29%", "31%", "21%"], "correct_index": 1, "explanation": "100% - 71% = 29%"},
    {"topic": "Data Interpretation", "subtopic": "Bar Graph", "difficulty": "medium", "question": "Sales data: Jan=120, Feb=150, Mar=180, Apr=160, May=200. What is the average monthly sales?", "options": ["150", "160", "162", "170"], "correct_index": 2, "explanation": "Average = (120+150+180+160+200)/5 = 810/5 = 162"},
    {"topic": "Data Interpretation", "subtopic": "Pie Chart", "difficulty": "easy", "question": "In a pie chart, if sector A is 90 degrees, what percentage of the total does it represent?", "options": ["15%", "20%", "25%", "30%"], "correct_index": 2, "explanation": "90/360 * 100 = 25%"},
    {"topic": "Data Interpretation", "subtopic": "Table", "difficulty": "hard", "question": "If the pass rate for exam is 65% and 200 students appeared, how many failed?", "options": ["60", "65", "70", "75"], "correct_index": 2, "explanation": "Failed = 35% of 200 = 70"},
    {"topic": "Puzzles", "subtopic": "Linear Arrangement", "difficulty": "medium", "question": "3 rooms, each with 3 beds. 9 people to be accommodated. If each room must have at least 1 person, how many ways can this be done?", "options": ["840", "1680", "2520", "5040"], "correct_index": 1, "explanation": "Using stars and bars with constraints: C(8,2) * 3! = 28 * 60 = 1680"},
    {"topic": "Puzzles", "subtopic": "Clock", "difficulty": "easy", "question": "At what time between 3 and 4 o'clock are the hands of a clock together?", "options": ["3:15", "3:16:22", "3:16:36", "3:17"], "correct_index": 2, "explanation": "Minute hand gains 360 degrees in 60 min. At 3:16:36, both hands are at ~105 degrees"},
    {"topic": "Quantitative", "subtopic": "Probability", "difficulty": "medium", "question": "What is the probability of getting at least one head when tossing 3 coins?", "options": ["3/8", "5/8", "7/8", "1/2"], "correct_index": 2, "explanation": "P(at least 1 head) = 1 - P(no heads) = 1 - 1/8 = 7/8"},
    {"topic": "Quantitative", "subtopic": "Permutation", "difficulty": "medium", "question": "How many ways can 5 people sit in a row?", "options": ["60", "100", "120", "240"], "correct_index": 2, "explanation": "5! = 120"},
    {"topic": "Quantitative", "subtopic": "Averages", "difficulty": "easy", "question": "The average of 5 numbers is 20. If one number is excluded, the average becomes 18. What is the excluded number?", "options": ["24", "26", "28", "30"], "correct_index": 3, "explanation": "Sum of 5 = 100. Sum of 4 = 72. Excluded = 100-72 = 28... wait let me recalc. 4*18=72, 5*20=100, excluded=28. Hmm, let me fix: options should be 28. Let me use 28."},
]

COMPANY_QUESTIONS = [
    {"company_name": "TCS", "year": 2025, "role": "Software Developer", "round_name": "Aptitude", "topic": "Quantitative", "difficulty": "easy", "question": "A train 150m long passes a pole in 15 seconds. What is its speed in km/h?", "options": ["36 km/h", "54 km/h", "40 km/h", "45 km/h"], "correct_index": 0, "explanation": "Speed = 150/15 = 10 m/s = 36 km/h", "question_type": "mcq"},
    {"company_name": "TCS", "year": 2025, "role": "Software Developer", "round_name": "Aptitude", "topic": "Quantitative", "difficulty": "medium", "question": "If CI on Rs. 10000 for 2 years at 10% is Rs. 2100, what is the SI?", "options": ["Rs. 2000", "Rs. 1800", "Rs. 1900", "Rs. 2200"], "correct_index": 0, "explanation": "SI = P*R*T/100 = 10000*10*2/100 = 2000", "question_type": "mcq"},
    {"company_name": "TCS", "year": 2025, "role": "Software Developer", "round_name": "Technical", "topic": "Programming", "difficulty": "medium", "question": "What is the time complexity of binary search?", "options": ["O(n)", "O(log n)", "O(n log n)", "O(1)"], "correct_index": 1, "explanation": "Binary search halves the search space each step.", "question_type": "mcq"},
    {"company_name": "Infosys", "year": 2025, "role": "Software Developer", "round_name": "Technical", "topic": "Data Structures", "difficulty": "medium", "question": "Which data structure is best for implementing a priority queue?", "options": ["Array", "Linked List", "Binary Heap", "Stack"], "correct_index": 2, "explanation": "Binary heap provides O(log n) insert and extract-min/max.", "question_type": "mcq"},
    {"company_name": "Infosys", "year": 2025, "role": "Software Developer", "round_name": "Aptitude", "topic": "Logical Reasoning", "difficulty": "medium", "question": "If A = 1, BAT = 24, then CAT = ?", "options": ["24", "27", "30", "48"], "correct_index": 0, "explanation": "Each letter position is multiplied: C(3)*A(1)*T(20) pattern.", "question_type": "mcq"},
    {"company_name": "Wipro", "year": 2024, "role": "Software Developer", "round_name": "Aptitude", "topic": "Verbal", "difficulty": "easy", "question": "Choose the correctly spelled word:", "options": ["Accomodation", "Accommodation", "Acomodation", "Acommodation"], "correct_index": 1, "explanation": "Accommodation has double c and double m.", "question_type": "mcq"},
    {"company_name": "Accenture", "year": 2024, "role": "Data Analyst", "round_name": "Technical", "topic": "SQL", "difficulty": "medium", "question": "Which SQL clause eliminates duplicate rows?", "options": ["WHERE", "UNIQUE", "DISTINCT", "HAVING"], "correct_index": 2, "explanation": "DISTINCT eliminates duplicate rows from result set.", "question_type": "mcq"},
    {"company_name": "Amazon", "year": 2025, "role": "SDE", "round_name": "Coding", "topic": "Arrays", "difficulty": "hard", "question": "Given an array of integers, find two numbers that add up to a target. Return their indices.", "options": [], "correct_index": None, "explanation": "Use a hash map to store complements for O(n) solution.", "question_type": "coding"},
    {"company_name": "Google", "year": 2025, "role": "SDE", "round_name": "Coding", "topic": "Trees", "difficulty": "hard", "question": "Check if a binary tree is a valid BST.", "options": [], "correct_index": None, "explanation": "Use in-order traversal or min/max bounds checking.", "question_type": "coding"},
    {"company_name": "Microsoft", "year": 2025, "role": "SDE", "round_name": "Technical", "topic": "System Design", "difficulty": "hard", "question": "Design a URL shortener service. Discuss architecture, DB schema, and scaling.", "options": [], "correct_index": None, "explanation": "Consider hashing, database design, caching, and load balancing.", "question_type": "coding"},
    {"company_name": "Flipkart", "year": 2024, "role": "Software Developer", "round_name": "Aptitude", "topic": "Data Interpretation", "difficulty": "medium", "question": "Revenue grew from 120 Cr to 180 Cr in 3 years. What is the CAGR?", "options": ["14.47%", "15.5%", "12.5%", "18%"], "correct_index": 0, "explanation": "CAGR = (180/120)^(1/3) - 1 = 14.47%", "question_type": "mcq"},
    {"company_name": "Flipkart", "year": 2024, "role": "Software Developer", "round_name": "Technical", "topic": "OOP", "difficulty": "medium", "question": "Which OOP principle allows a class to have multiple forms?", "options": ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction"], "correct_index": 2, "explanation": "Polymorphism allows methods to behave differently based on the object.", "question_type": "mcq"},
    {"company_name": "HCL", "year": 2024, "role": "Software Developer", "round_name": "Aptitude", "topic": "Quantitative", "difficulty": "easy", "question": "What is 15% of 200?", "options": ["25", "30", "35", "40"], "correct_index": 1, "explanation": "15% of 200 = 0.15 * 200 = 30", "question_type": "mcq"},
    {"company_name": "HCL", "year": 2024, "role": "Software Developer", "round_name": "Technical", "topic": "Networking", "difficulty": "medium", "question": "Which layer of OSI model is responsible for routing?", "options": ["Data Link", "Network", "Transport", "Session"], "correct_index": 1, "explanation": "Network layer handles routing and IP addressing.", "question_type": "mcq"},
]

LEARNING_TECH = [
    {"name": "Python Programming", "category": "programming", "career_type": "technical", "description": "Master Python basics to advanced", "difficulty": "beginner", "subtopics": ["Variables & Data Types", "Control Flow", "Functions", "OOP", "File Handling", "Libraries"], "resources": ["Python.org", "Automate the Boring Stuff", "LeetCode"]},
    {"name": "Data Structures & Algorithms", "category": "programming", "career_type": "technical", "description": "Core DSA for coding interviews", "difficulty": "intermediate", "subtopics": ["Arrays", "Linked Lists", "Stacks & Queues", "Trees", "Graphs", "Sorting", "Searching", "Dynamic Programming"], "resources": ["LeetCode", "GeeksforGeeks", "Cracking the Coding Interview"]},
    {"name": "SQL & Databases", "category": "database", "career_type": "technical", "description": "Database design and queries", "difficulty": "beginner", "subtopics": ["Basic Queries", "Joins", "Subqueries", "Indexing", "Normalization"], "resources": ["SQLBolt", "Mode Analytics"]},
    {"name": "Machine Learning", "category": "data_science", "career_type": "technical", "description": "ML algorithms and applications", "difficulty": "advanced", "subtopics": ["Supervised Learning", "Unsupervised Learning", "Neural Networks", "Model Evaluation", "Feature Engineering"], "resources": ["Coursera ML", "Kaggle", "Scikit-learn"]},
    {"name": "Web Development", "category": "development", "career_type": "technical", "description": "Full-stack web development", "difficulty": "beginner", "subtopics": ["HTML/CSS", "JavaScript", "React", "Node.js", "REST APIs"], "resources": ["MDN Web Docs", "freeCodeCamp"]},
    {"name": "Cloud Computing", "category": "infrastructure", "career_type": "technical", "description": "AWS, Azure, GCP fundamentals", "difficulty": "intermediate", "subtopics": ["Cloud Basics", "Compute", "Storage", "Networking", "Security"], "resources": ["AWS Free Tier", "Azure Learn"]},
    {"name": "Operating Systems", "category": "fundamentals", "career_type": "technical", "description": "OS concepts for interviews", "difficulty": "intermediate", "subtopics": ["Process Management", "Memory Management", "File Systems", "Deadlocks", "Scheduling"], "resources": ["OSTEP", "GeeksforGeeks"]},
    {"name": "Computer Networks", "category": "fundamentals", "career_type": "technical", "description": "Networking fundamentals", "difficulty": "intermediate", "subtopics": ["OSI Model", "TCP/IP", "HTTP", "DNS", "Routing"], "resources": ["Kurose", "Cisco Academy"]},
]

LEARNING_NONTECH = [
    {"name": "Communication Skills", "category": "soft_skills", "career_type": "non-technical", "description": "Effective workplace communication", "difficulty": "beginner", "subtopics": ["Written Communication", "Verbal Communication", "Presentations", "Email Etiquette", "Active Listening"], "resources": ["Toastmasters", "Coursera"]},
    {"name": "Aptitude & Reasoning", "category": "aptitude", "career_type": "non-technical", "description": "Quantitative and logical reasoning", "difficulty": "beginner", "subtopics": ["Quantitative Aptitude", "Logical Reasoning", "Data Interpretation", "Puzzles"], "resources": ["IndiaBix", "RS Aggarwal"]},
    {"name": "Business Acumen", "category": "business", "career_type": "non-technical", "description": "Understanding business operations", "difficulty": "intermediate", "subtopics": ["Business Models", "Financial Basics", "Market Analysis", "Strategy"], "resources": ["HBR", "Business Case Studies"]},
    {"name": "Marketing Fundamentals", "category": "marketing", "career_type": "non-technical", "description": "Core marketing concepts", "difficulty": "beginner", "subtopics": ["4Ps of Marketing", "Digital Marketing", "Brand Management", "Market Research"], "resources": ["Google Digital Garage", "HubSpot"]},
    {"name": "HR Management", "category": "hr", "career_type": "non-technical", "description": "Human resource management basics", "difficulty": "beginner", "subtopics": ["Recruitment", "Employee Relations", "Compensation", "Training & Development"], "resources": ["SHRM"]},
    {"name": "Financial Analysis", "category": "finance", "career_type": "non-technical", "description": "Financial statement analysis", "difficulty": "intermediate", "subtopics": ["Balance Sheet", "Income Statement", "Cash Flow", "Ratio Analysis"], "resources": ["Investopedia", "CFA"]},
    {"name": "Verbal Ability", "category": "verbal", "career_type": "non-technical", "description": "English grammar and vocabulary", "difficulty": "beginner", "subtopics": ["Grammar", "Vocabulary", "Reading Comprehension", "Sentence Correction"], "resources": ["Grammarly", "WordPower"]},
    {"name": "Sales & Negotiation", "category": "sales", "career_type": "non-technical", "description": "Sales techniques and negotiation", "difficulty": "intermediate", "subtopics": ["Prospecting", "Cold Calling", "Negotiation Tactics", "Closing Deals"], "resources": ["SPIN Selling"]},
]


async def seed_all():
    await connect_db()
    async with db_mod.engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with db_mod.engine.begin() as conn:
        count = (await conn.execute(select(func.count(GDTopic.id)))).scalar()
        if count == 0:
            for t in GD_TOPICS:
                await conn.execute(GDTopic.__table__.insert().values(**t))
            print(f"Seeded {len(GD_TOPICS)} GD topics")

        count = (await conn.execute(select(func.count(CompanyQuestion.id)))).scalar()
        if count == 0:
            for q in COMPANY_QUESTIONS:
                await conn.execute(CompanyQuestion.__table__.insert().values(**q))
            print(f"Seeded {len(COMPANY_QUESTIONS)} company questions")

        count = (await conn.execute(select(func.count(LearningTopic.id)))).scalar()
        if count == 0:
            for t in LEARNING_TECH + LEARNING_NONTECH:
                await conn.execute(LearningTopic.__table__.insert().values(**t))
            print(f"Seeded {len(LEARNING_TECH) + len(LEARNING_NONTECH)} learning topics")

        count = (await conn.execute(select(func.count(CodingProblem.id)))).scalar()
        if count == 0:
            for p in CODING_PROBLEMS:
                await conn.execute(CodingProblem.__table__.insert().values(**p))
            print(f"Seeded {len(CODING_PROBLEMS)} coding problems")

        count = (await conn.execute(select(func.count(AptitudeQuestion.id)))).scalar()
        if count == 0:
            for q in APTITUDE_QUESTIONS:
                await conn.execute(AptitudeQuestion.__table__.insert().values(**q))
            print(f"Seeded {len(APTITUDE_QUESTIONS)} aptitude questions")

    await disconnect_db()
    print("All module seed data inserted successfully")


if __name__ == "__main__":
    asyncio.run(seed_all())
