import { useState } from 'react'
import { QRCodeSVG } from 'qrcode.react'
import { Copy, Share2, Printer, Download, Check, CreditCard } from 'lucide-react'
import { useToast } from '../ui/ToastProvider'

export default function StudentIdCard({ profile, user }) {
  const { toast } = useToast()
  const [copied, setCopied] = useState(false)

  const p = profile.personal || {}
  const c = profile.college || {}
  const name = user?.name || ''
  const email = user?.email || ''

  const qrValue = JSON.stringify({
    uid: user?.uid || '',
    name,
    roll: c.roll_number || '',
    branch: c.branch || '',
    college: c.college_name || '',
    email,
  })

  const detailText = [
    `Name: ${name}`,
    `Roll: ${c.roll_number || '—'}`,
    `Branch: ${c.branch || '—'}`,
    `College: ${c.college_name || '—'}`,
    `Email: ${email}`,
  ].join('\n')

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(detailText)
      setCopied(true)
      toast({ type: 'success', message: 'Profile details copied' })
      setTimeout(() => setCopied(false), 2000)
    } catch {
      toast({ type: 'error', message: 'Copy failed' })
    }
  }

  const share = async () => {
    const text = `${name}\n${c.branch || ''}${c.branch && c.college_name ? ' @ ' : ''}${c.college_name || ''}\n${email}`
    try {
      if (navigator.share) {
        await navigator.share({ title: `${name} - PlaceX`, text })
      } else {
        await copy()
      }
    } catch (err) {
      if (err.name !== 'AbortError') {
        await copy()
      }
    }
  }

  const downloadPdf = () => {
    const w = window.open('', '_blank')
    if (!w) return
    w.document.write(`
      <!DOCTYPE html>
      <html><head><title>${name} - Student ID</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #111; }
        .card { border: 2px solid #2563eb; border-radius: 16px; padding: 28px; max-width: 520px; }
        .header { display: flex; align-items: center; gap: 16px; border-bottom: 1px solid #e5e7eb; padding-bottom: 16px; }
        .avatar { width: 72px; height: 72px; border-radius: 50%; object-fit: cover; background: #eff6ff; display: flex; align-items: center; justify-content: center; font-size: 26px; color: #2563eb; font-weight: bold; }
        h1 { font-size: 22px; margin: 0; }
        .sub { color: #6b7280; font-size: 13px; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-top: 18px; font-size: 13px; }
        .grid b { display: block; color: #6b7280; font-size: 11px; text-transform: uppercase; letter-spacing: .5px; }
        .qr { display: flex; align-items: center; gap: 20px; margin-top: 20px; padding-top: 16px; border-top: 1px solid #e5e7eb; }
        .footer { margin-top: 24px; font-size: 11px; color: #9ca3af; text-align: center; }
      </style></head><body>
      <div class="card">
        <div class="header">
          <div class="avatar">${profile.photo ? `<img class="avatar" src="${profile.photo}" alt="" />` : (name[0] || '?').toUpperCase()}</div>
          <div><h1>${name}</h1><div class="sub">${c.roll_number ? `Roll: ${c.roll_number}` : ''}</div><div class="sub">${email}</div></div>
        </div>
        <div class="grid">
          <div><b>Branch</b>${c.branch || '—'}</div>
          <div><b>Degree</b>${c.degree || '—'}</div>
          <div><b>College</b>${c.college_name || '—'}</div>
          <div><b>CGPA</b>${c.cgpa || '—'}</div>
          <div><b>Blood Group</b>${p.blood_group || '—'}</div>
          <div><b>Nationality</b>${p.nationality || '—'}</div>
        </div>
        <div class="footer">Generated by PlaceX · ${new Date().toLocaleDateString()}</div>
      </div>
      <script>window.onload = function(){ setTimeout(function(){ window.print(); }, 300); }</script>
      </body></html>
    `)
    w.document.close()
    toast({ type: 'success', message: 'PDF download started (choose "Save as PDF")' })
  }

  const actions = [
    { label: 'Copy', icon: copied ? Check : Copy, onClick: copy, active: copied },
    { label: 'Share', icon: Share2, onClick: share },
    { label: 'Print', icon: Printer, onClick: () => downloadPdf() },
    { label: 'PDF', icon: Download, onClick: downloadPdf },
  ]

  return (
    <div className="card dark:bg-gray-900 dark:border-gray-800">
      <h2 className="font-semibold text-gray-800 dark:text-white flex items-center gap-2 mb-4">
        <CreditCard size={18} className="text-primary-600" /> Student ID Card
      </h2>
      <div className="flex flex-col sm:flex-row items-center gap-5 bg-gradient-to-br from-primary-50 to-white dark:from-gray-800 dark:to-gray-900 border border-primary-100 dark:border-gray-700 rounded-xl p-5">
        <div className="flex items-center gap-4">
          {profile.photo ? (
            <img src={profile.photo} alt={name} className="w-16 h-16 rounded-full object-cover border-2 border-primary-200" />
          ) : (
            <div className="w-16 h-16 rounded-full bg-primary-100 text-primary-700 flex items-center justify-center text-2xl font-bold">
              {(name[0] || '?').toUpperCase()}
            </div>
          )}
          <div>
            <div className="font-bold text-gray-900 dark:text-white">{name}</div>
            <div className="text-sm text-gray-500 dark:text-gray-400">
              {c.roll_number ? `Roll: ${c.roll_number}` : 'Roll: —'} · {c.branch || '—'}
            </div>
            <div className="text-xs text-gray-400 dark:text-gray-500">{c.college_name || ''}</div>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-lg p-2 border border-gray-200 dark:border-gray-700 shrink-0">
          <QRCodeSVG value={qrValue} size={88} level="M" />
        </div>
      </div>
      <div className="flex flex-wrap gap-2 mt-4">
        {actions.map((a) => {
          const Icon = a.icon
          return (
            <button
              key={a.label}
              onClick={a.onClick}
              className={`flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-lg transition-colors ${
                a.active
                  ? 'bg-green-100 text-green-700'
                  : 'bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700'
              }`}
            >
              <Icon size={14} /> {a.label}
            </button>
          )
        })}
      </div>
    </div>
  )
}
